# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrderDetails")

model.instance <- OrderDetails$new()

test_that("symbol", {
  # tests for the property `symbol` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`symbol`, "EXPECTED_RESULT")
})

test_that("orderId", {
  # tests for the property `orderId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`orderId`, "EXPECTED_RESULT")
})

test_that("orderListId", {
  # tests for the property `orderListId` (integer)
  # Unless OCO, value will be -1

  # uncomment below to test the property
  #expect_equal(model.instance$`orderListId`, "EXPECTED_RESULT")
})

test_that("clientOrderId", {
  # tests for the property `clientOrderId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`clientOrderId`, "EXPECTED_RESULT")
})

test_that("price", {
  # tests for the property `price` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`price`, "EXPECTED_RESULT")
})

test_that("origQty", {
  # tests for the property `origQty` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`origQty`, "EXPECTED_RESULT")
})

test_that("executedQty", {
  # tests for the property `executedQty` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`executedQty`, "EXPECTED_RESULT")
})

test_that("cummulativeQuoteQty", {
  # tests for the property `cummulativeQuoteQty` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`cummulativeQuoteQty`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("timeInForce", {
  # tests for the property `timeInForce` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`timeInForce`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("side", {
  # tests for the property `side` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`side`, "EXPECTED_RESULT")
})

test_that("stopPrice", {
  # tests for the property `stopPrice` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`stopPrice`, "EXPECTED_RESULT")
})

test_that("icebergQty", {
  # tests for the property `icebergQty` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`icebergQty`, "EXPECTED_RESULT")
})

test_that("time", {
  # tests for the property `time` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`time`, "EXPECTED_RESULT")
})

test_that("updateTime", {
  # tests for the property `updateTime` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`updateTime`, "EXPECTED_RESULT")
})

test_that("isWorking", {
  # tests for the property `isWorking` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isWorking`, "EXPECTED_RESULT")
})

test_that("origQuoteOrderQty", {
  # tests for the property `origQuoteOrderQty` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`origQuoteOrderQty`, "EXPECTED_RESULT")
})

