# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20014")

model.instance <- InlineResponse20014$new()

test_that("assetFullName", {
  # tests for the property `assetFullName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assetFullName`, "EXPECTED_RESULT")
})

test_that("assetName", {
  # tests for the property `assetName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assetName`, "EXPECTED_RESULT")
})

test_that("isBorrowable", {
  # tests for the property `isBorrowable` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isBorrowable`, "EXPECTED_RESULT")
})

test_that("isMortgageable", {
  # tests for the property `isMortgageable` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isMortgageable`, "EXPECTED_RESULT")
})

test_that("userMinBorrow", {
  # tests for the property `userMinBorrow` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`userMinBorrow`, "EXPECTED_RESULT")
})

test_that("userMinRepay", {
  # tests for the property `userMinRepay` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`userMinRepay`, "EXPECTED_RESULT")
})

