# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20089Data")

model.instance <- InlineResponse20089Data$new()

test_that("accountProfits", {
  # tests for the property `accountProfits` (array[InlineResponse20089DataAccountProfits])

  # uncomment below to test the property
  #expect_equal(model.instance$`accountProfits`, "EXPECTED_RESULT")
})

test_that("totalNum", {
  # tests for the property `totalNum` (integer)
  # Total Rows

  # uncomment below to test the property
  #expect_equal(model.instance$`totalNum`, "EXPECTED_RESULT")
})

test_that("pageSize", {
  # tests for the property `pageSize` (integer)
  # Rows per page

  # uncomment below to test the property
  #expect_equal(model.instance$`pageSize`, "EXPECTED_RESULT")
})

