# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20050")

model.instance <- InlineResponse20050$new()

test_that("success", {
  # tests for the property `success` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`success`, "EXPECTED_RESULT")
})

test_that("txnId", {
  # tests for the property `txnId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`txnId`, "EXPECTED_RESULT")
})

