# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20028")

model.instance <- InlineResponse20028$new()

test_that("asset", {
  # tests for the property `asset` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`asset`, "EXPECTED_RESULT")
})

test_that("dailyInterestRate", {
  # tests for the property `dailyInterestRate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`dailyInterestRate`, "EXPECTED_RESULT")
})

test_that("timestamp", {
  # tests for the property `timestamp` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`timestamp`, "EXPECTED_RESULT")
})

test_that("vipLevel", {
  # tests for the property `vipLevel` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`vipLevel`, "EXPECTED_RESULT")
})

