# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SnapshotSpotDataBalances")

model.instance <- SnapshotSpotDataBalances$new()

test_that("asset", {
  # tests for the property `asset` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`asset`, "EXPECTED_RESULT")
})

test_that("free", {
  # tests for the property `free` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`free`, "EXPECTED_RESULT")
})

test_that("locked", {
  # tests for the property `locked` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`locked`, "EXPECTED_RESULT")
})

