# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SubAccountUSDTFuturesDetailsFutureAccountResp")

model.instance <- SubAccountUSDTFuturesDetailsFutureAccountResp$new()

test_that("email", {
  # tests for the property `email` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("assets", {
  # tests for the property `assets` (array[InlineResponse20060Assets])

  # uncomment below to test the property
  #expect_equal(model.instance$`assets`, "EXPECTED_RESULT")
})

test_that("canDeposit", {
  # tests for the property `canDeposit` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`canDeposit`, "EXPECTED_RESULT")
})

test_that("canTrade", {
  # tests for the property `canTrade` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`canTrade`, "EXPECTED_RESULT")
})

test_that("canWithdraw", {
  # tests for the property `canWithdraw` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`canWithdraw`, "EXPECTED_RESULT")
})

test_that("feeTier", {
  # tests for the property `feeTier` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`feeTier`, "EXPECTED_RESULT")
})

test_that("maxWithdrawAmount", {
  # tests for the property `maxWithdrawAmount` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`maxWithdrawAmount`, "EXPECTED_RESULT")
})

test_that("totalInitialMargin", {
  # tests for the property `totalInitialMargin` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalInitialMargin`, "EXPECTED_RESULT")
})

test_that("totalMaintenanceMargin", {
  # tests for the property `totalMaintenanceMargin` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalMaintenanceMargin`, "EXPECTED_RESULT")
})

test_that("totalMarginBalance", {
  # tests for the property `totalMarginBalance` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalMarginBalance`, "EXPECTED_RESULT")
})

test_that("totalOpenOrderInitialMargin", {
  # tests for the property `totalOpenOrderInitialMargin` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalOpenOrderInitialMargin`, "EXPECTED_RESULT")
})

test_that("totalPositionInitialMargin", {
  # tests for the property `totalPositionInitialMargin` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalPositionInitialMargin`, "EXPECTED_RESULT")
})

test_that("totalUnrealizedProfit", {
  # tests for the property `totalUnrealizedProfit` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalUnrealizedProfit`, "EXPECTED_RESULT")
})

test_that("totalWalletBalance", {
  # tests for the property `totalWalletBalance` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalWalletBalance`, "EXPECTED_RESULT")
})

test_that("updateTime", {
  # tests for the property `updateTime` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`updateTime`, "EXPECTED_RESULT")
})

