# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SubAccountCOINFuturesSummaryDeliveryAccountSummaryRespSubAccountList")

model.instance <- SubAccountCOINFuturesSummaryDeliveryAccountSummaryRespSubAccountList$new()

test_that("email", {
  # tests for the property `email` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("totalMarginBalance", {
  # tests for the property `totalMarginBalance` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalMarginBalance`, "EXPECTED_RESULT")
})

test_that("totalUnrealizedProfit", {
  # tests for the property `totalUnrealizedProfit` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalUnrealizedProfit`, "EXPECTED_RESULT")
})

test_that("totalWalletBalance", {
  # tests for the property `totalWalletBalance` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalWalletBalance`, "EXPECTED_RESULT")
})

test_that("asset", {
  # tests for the property `asset` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`asset`, "EXPECTED_RESULT")
})

