# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20058SubAccountList")

model.instance <- InlineResponse20058SubAccountList$new()

test_that("email", {
  # tests for the property `email` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("totalAssetOfBtc", {
  # tests for the property `totalAssetOfBtc` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalAssetOfBtc`, "EXPECTED_RESULT")
})

test_that("totalLiabilityOfBtc", {
  # tests for the property `totalLiabilityOfBtc` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalLiabilityOfBtc`, "EXPECTED_RESULT")
})

test_that("totalNetAssetOfBtc", {
  # tests for the property `totalNetAssetOfBtc` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalNetAssetOfBtc`, "EXPECTED_RESULT")
})

