# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse200108")

model.instance <- InlineResponse200108$new()

test_that("swapId", {
  # tests for the property `swapId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`swapId`, "EXPECTED_RESULT")
})

test_that("swapTime", {
  # tests for the property `swapTime` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`swapTime`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (integer)
  # 0: pending, 1: success, 2: failed

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("quoteAsset", {
  # tests for the property `quoteAsset` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`quoteAsset`, "EXPECTED_RESULT")
})

test_that("baseAsset", {
  # tests for the property `baseAsset` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`baseAsset`, "EXPECTED_RESULT")
})

test_that("quoteQty", {
  # tests for the property `quoteQty` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`quoteQty`, "EXPECTED_RESULT")
})

test_that("baseQty", {
  # tests for the property `baseQty` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`baseQty`, "EXPECTED_RESULT")
})

test_that("price", {
  # tests for the property `price` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`price`, "EXPECTED_RESULT")
})

test_that("fee", {
  # tests for the property `fee` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`fee`, "EXPECTED_RESULT")
})

