# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MarginOrderResponseFull")

model.instance <- MarginOrderResponseFull$new()

test_that("symbol", {
  # tests for the property `symbol` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`symbol`, "EXPECTED_RESULT")
})

test_that("orderId", {
  # tests for the property `orderId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`orderId`, "EXPECTED_RESULT")
})

test_that("clientOrderId", {
  # tests for the property `clientOrderId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`clientOrderId`, "EXPECTED_RESULT")
})

test_that("transactTime", {
  # tests for the property `transactTime` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`transactTime`, "EXPECTED_RESULT")
})

test_that("price", {
  # tests for the property `price` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`price`, "EXPECTED_RESULT")
})

test_that("origQty", {
  # tests for the property `origQty` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`origQty`, "EXPECTED_RESULT")
})

test_that("executedQty", {
  # tests for the property `executedQty` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`executedQty`, "EXPECTED_RESULT")
})

test_that("cummulativeQuoteQty", {
  # tests for the property `cummulativeQuoteQty` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`cummulativeQuoteQty`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("timeInForce", {
  # tests for the property `timeInForce` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`timeInForce`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("side", {
  # tests for the property `side` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`side`, "EXPECTED_RESULT")
})

test_that("marginBuyBorrowAmount", {
  # tests for the property `marginBuyBorrowAmount` (numeric)
  # will not return if no margin trade happens

  # uncomment below to test the property
  #expect_equal(model.instance$`marginBuyBorrowAmount`, "EXPECTED_RESULT")
})

test_that("marginBuyBorrowAsset", {
  # tests for the property `marginBuyBorrowAsset` (character)
  # will not return if no margin trade happens

  # uncomment below to test the property
  #expect_equal(model.instance$`marginBuyBorrowAsset`, "EXPECTED_RESULT")
})

test_that("isIsolated", {
  # tests for the property `isIsolated` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isIsolated`, "EXPECTED_RESULT")
})

test_that("fills", {
  # tests for the property `fills` (array[OrderResponseFullFills])

  # uncomment below to test the property
  #expect_equal(model.instance$`fills`, "EXPECTED_RESULT")
})

