# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse200103Data")

model.instance <- InlineResponse200103Data$new()

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("userName", {
  # tests for the property `userName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`userName`, "EXPECTED_RESULT")
})

test_that("list", {
  # tests for the property `list` (array[InlineResponse200103List])

  # uncomment below to test the property
  #expect_equal(model.instance$`list`, "EXPECTED_RESULT")
})

