# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20091Data")

model.instance <- InlineResponse20091Data$new()

test_that("configDetails", {
  # tests for the property `configDetails` (array[InlineResponse20091DataConfigDetails])

  # uncomment below to test the property
  #expect_equal(model.instance$`configDetails`, "EXPECTED_RESULT")
})

test_that("totalNum", {
  # tests for the property `totalNum` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalNum`, "EXPECTED_RESULT")
})

test_that("pageSize", {
  # tests for the property `pageSize` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pageSize`, "EXPECTED_RESULT")
})

