# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20040UserAssetDribbletDetails")

model.instance <- InlineResponse20040UserAssetDribbletDetails$new()

test_that("transId", {
  # tests for the property `transId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`transId`, "EXPECTED_RESULT")
})

test_that("serviceChargeAmount", {
  # tests for the property `serviceChargeAmount` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`serviceChargeAmount`, "EXPECTED_RESULT")
})

test_that("amount", {
  # tests for the property `amount` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`amount`, "EXPECTED_RESULT")
})

test_that("operateTime", {
  # tests for the property `operateTime` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`operateTime`, "EXPECTED_RESULT")
})

test_that("transferedAmount", {
  # tests for the property `transferedAmount` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`transferedAmount`, "EXPECTED_RESULT")
})

test_that("fromAsset", {
  # tests for the property `fromAsset` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`fromAsset`, "EXPECTED_RESULT")
})

