# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20096List")

model.instance <- InlineResponse20096List$new()

test_that("time", {
  # tests for the property `time` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`time`, "EXPECTED_RESULT")
})

test_that("hashrate", {
  # tests for the property `hashrate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`hashrate`, "EXPECTED_RESULT")
})

test_that("reject", {
  # tests for the property `reject` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`reject`, "EXPECTED_RESULT")
})

