# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MiningApi")

api.instance <- MiningApi$new()

test_that("SapiV1MiningHashTransferConfigCancelPost", {
  # tests for SapiV1MiningHashTransferConfigCancelPost
  # base path: https://api.binance.com
  # Cancel Hashrate Resale configuration (USER_DATA)
  # Weight(IP): 5
  # @param config.id character Mining ID
  # @param user.name character Mining Account
  # @param timestamp integer UTC timestamp in ms
  # @param signature character Signature
  # @param recv.window integer The value cannot be greater than 60000 (optional)
  # @return [InlineResponse20094]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SapiV1MiningHashTransferConfigDetailsListGet", {
  # tests for SapiV1MiningHashTransferConfigDetailsListGet
  # base path: https://api.binance.com
  # Hashrate Resale List (USER_DATA)
  # Weight(IP): 5
  # @param timestamp integer UTC timestamp in ms
  # @param signature character Signature
  # @param page.index integer Page number, default is first page, start form 1 (optional)
  # @param page.size character Number of pages, minimum 10, maximum 200 (optional)
  # @param recv.window integer The value cannot be greater than 60000 (optional)
  # @return [InlineResponse20091]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SapiV1MiningHashTransferConfigPost", {
  # tests for SapiV1MiningHashTransferConfigPost
  # base path: https://api.binance.com
  # Hashrate Resale Request (USER_DATA)
  # Weight(IP): 5
  # @param user.name character Mining Account
  # @param algo character Algorithm(sha256)
  # @param to.pool.user character Mining Account
  # @param hash.rate character Resale hashrate h/s must be transferred (BTC is greater than 500000000000 ETH is greater than 500000)
  # @param timestamp integer UTC timestamp in ms
  # @param signature character Signature
  # @param start.date character Search date, millisecond timestamp, while empty query all (optional)
  # @param end.date character Search date, millisecond timestamp, while empty query all (optional)
  # @param recv.window integer The value cannot be greater than 60000 (optional)
  # @return [InlineResponse20093]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SapiV1MiningHashTransferProfitDetailsGet", {
  # tests for SapiV1MiningHashTransferProfitDetailsGet
  # base path: https://api.binance.com
  # Hashrate Resale Details (USER_DATA)
  # Weight(IP): 5
  # @param config.id character Mining ID
  # @param user.name character Mining Account
  # @param timestamp integer UTC timestamp in ms
  # @param signature character Signature
  # @param page.index integer Page number, default is first page, start form 1 (optional)
  # @param page.size character Number of pages, minimum 10, maximum 200 (optional)
  # @param recv.window integer The value cannot be greater than 60000 (optional)
  # @return [InlineResponse20092]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SapiV1MiningPaymentListGet", {
  # tests for SapiV1MiningPaymentListGet
  # base path: https://api.binance.com
  # Earnings List (USER_DATA)
  # Weight(IP): 5
  # @param algo character Algorithm(sha256)
  # @param user.name character Mining Account
  # @param timestamp integer UTC timestamp in ms
  # @param signature character Signature
  # @param coin character Coin name (optional)
  # @param start.date character Search date, millisecond timestamp, while empty query all (optional)
  # @param end.date character Search date, millisecond timestamp, while empty query all (optional)
  # @param page.index integer Page number, default is first page, start form 1 (optional)
  # @param page.size character Number of pages, minimum 10, maximum 200 (optional)
  # @param recv.window integer The value cannot be greater than 60000 (optional)
  # @return [InlineResponse20089]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SapiV1MiningPaymentOtherGet", {
  # tests for SapiV1MiningPaymentOtherGet
  # base path: https://api.binance.com
  # Extra Bonus List (USER_DATA)
  # Weight(IP): 5
  # @param algo character Algorithm(sha256)
  # @param user.name character Mining Account
  # @param timestamp integer UTC timestamp in ms
  # @param signature character Signature
  # @param coin character Coin name (optional)
  # @param start.date character Search date, millisecond timestamp, while empty query all (optional)
  # @param end.date character Search date, millisecond timestamp, while empty query all (optional)
  # @param page.index integer Page number, default is first page, start form 1 (optional)
  # @param page.size character Number of pages, minimum 10, maximum 200 (optional)
  # @param recv.window integer The value cannot be greater than 60000 (optional)
  # @return [InlineResponse20090]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SapiV1MiningPubAlgoListGet", {
  # tests for SapiV1MiningPubAlgoListGet
  # base path: https://api.binance.com
  # Acquiring Algorithm (MARKET_DATA)
  # Weight(IP): 1
  # @param timestamp integer UTC timestamp in ms
  # @param signature character Signature
  # @param recv.window integer The value cannot be greater than 60000 (optional)
  # @return [InlineResponse20085]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SapiV1MiningPubCoinListGet", {
  # tests for SapiV1MiningPubCoinListGet
  # base path: https://api.binance.com
  # Acquiring CoinName (MARKET_DATA)
  # Weight(IP): 1
  # @param timestamp integer UTC timestamp in ms
  # @param signature character Signature
  # @param recv.window integer The value cannot be greater than 60000 (optional)
  # @return [InlineResponse20086]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SapiV1MiningStatisticsUserListGet", {
  # tests for SapiV1MiningStatisticsUserListGet
  # base path: https://api.binance.com
  # Account List (USER_DATA)
  # Weight(IP): 5
  # @param algo character Algorithm(sha256)
  # @param user.name character Mining Account
  # @param timestamp integer UTC timestamp in ms
  # @param signature character Signature
  # @param recv.window integer The value cannot be greater than 60000 (optional)
  # @return [InlineResponse20096]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SapiV1MiningStatisticsUserStatusGet", {
  # tests for SapiV1MiningStatisticsUserStatusGet
  # base path: https://api.binance.com
  # Statistic List (USER_DATA)
  # Weight(IP): 5
  # @param algo character Algorithm(sha256)
  # @param user.name character Mining Account
  # @param timestamp integer UTC timestamp in ms
  # @param signature character Signature
  # @param recv.window integer The value cannot be greater than 60000 (optional)
  # @return [InlineResponse20095]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SapiV1MiningWorkerDetailGet", {
  # tests for SapiV1MiningWorkerDetailGet
  # base path: https://api.binance.com
  # Request for Detail Miner List (USER_DATA)
  # Weight(IP): 5
  # @param algo character Algorithm(sha256)
  # @param user.name character Mining Account
  # @param worker.name character Miner’s name
  # @param timestamp integer UTC timestamp in ms
  # @param signature character Signature
  # @param recv.window integer The value cannot be greater than 60000 (optional)
  # @return [InlineResponse20087]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SapiV1MiningWorkerListGet", {
  # tests for SapiV1MiningWorkerListGet
  # base path: https://api.binance.com
  # Request for Miner List (USER_DATA)
  # Weight(IP): 5
  # @param algo character Algorithm(sha256)
  # @param user.name character Mining Account
  # @param timestamp integer UTC timestamp in ms
  # @param signature character Signature
  # @param page.index integer Page number, default is first page, start form 1 (optional)
  # @param sort integer sort sequence（default=0）0 positive sequence, 1 negative sequence (optional)
  # @param sort.column integer Sort by( default 1): 1: miner name, 2: real-time computing power, 3: daily average computing power, 4: real-time rejection rate, 5: last submission time (optional)
  # @param worker.status integer miners status（default=0）0 all, 1 valid, 2 invalid, 3 failure (optional)
  # @param recv.window integer The value cannot be greater than 60000 (optional)
  # @return [InlineResponse20088]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

