# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20043CTR")

model.instance <- InlineResponse20043CTR$new()

test_that("minWithdrawAmount", {
  # tests for the property `minWithdrawAmount` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`minWithdrawAmount`, "EXPECTED_RESULT")
})

test_that("depositStatus", {
  # tests for the property `depositStatus` (character)
  # deposit status (false if ALL of networks&#39; are false)

  # uncomment below to test the property
  #expect_equal(model.instance$`depositStatus`, "EXPECTED_RESULT")
})

test_that("withdrawFee", {
  # tests for the property `withdrawFee` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`withdrawFee`, "EXPECTED_RESULT")
})

test_that("withdrawStatus", {
  # tests for the property `withdrawStatus` (character)
  # withdrawStatus status (false if ALL of networks&#39; are false)

  # uncomment below to test the property
  #expect_equal(model.instance$`withdrawStatus`, "EXPECTED_RESULT")
})

test_that("depositTip", {
  # tests for the property `depositTip` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`depositTip`, "EXPECTED_RESULT")
})

