# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BswapRmvLiquidityPreviewSingle")

model.instance <- BswapRmvLiquidityPreviewSingle$new()

test_that("quoteAsset", {
  # tests for the property `quoteAsset` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`quoteAsset`, "EXPECTED_RESULT")
})

test_that("quoteAmt", {
  # tests for the property `quoteAmt` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`quoteAmt`, "EXPECTED_RESULT")
})

test_that("price", {
  # tests for the property `price` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`price`, "EXPECTED_RESULT")
})

test_that("slippage", {
  # tests for the property `slippage` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`slippage`, "EXPECTED_RESULT")
})

test_that("fee", {
  # tests for the property `fee` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`fee`, "EXPECTED_RESULT")
})

