# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20042")

model.instance <- InlineResponse20042$new()

test_that("total", {
  # tests for the property `total` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`total`, "EXPECTED_RESULT")
})

test_that("rows", {
  # tests for the property `rows` (array[InlineResponse20042Rows])

  # uncomment below to test the property
  #expect_equal(model.instance$`rows`, "EXPECTED_RESULT")
})

