# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Error")

model.instance <- Error$new()

test_that("code", {
  # tests for the property `code` (integer)
  # Error code

  # uncomment below to test the property
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

test_that("msg", {
  # tests for the property `msg` (character)
  # Error message

  # uncomment below to test the property
  #expect_equal(model.instance$`msg`, "EXPECTED_RESULT")
})

