# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SnapshotFuturesSnapshotVos")

model.instance <- SnapshotFuturesSnapshotVos$new()

test_that("data", {
  # tests for the property `data` (SnapshotFuturesData)

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("updateTime", {
  # tests for the property `updateTime` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`updateTime`, "EXPECTED_RESULT")
})

