# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20019")

model.instance <- InlineResponse20019$new()

test_that("borrowEnabled", {
  # tests for the property `borrowEnabled` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`borrowEnabled`, "EXPECTED_RESULT")
})

test_that("marginLevel", {
  # tests for the property `marginLevel` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`marginLevel`, "EXPECTED_RESULT")
})

test_that("totalAssetOfBtc", {
  # tests for the property `totalAssetOfBtc` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalAssetOfBtc`, "EXPECTED_RESULT")
})

test_that("totalLiabilityOfBtc", {
  # tests for the property `totalLiabilityOfBtc` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalLiabilityOfBtc`, "EXPECTED_RESULT")
})

test_that("totalNetAssetOfBtc", {
  # tests for the property `totalNetAssetOfBtc` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalNetAssetOfBtc`, "EXPECTED_RESULT")
})

test_that("tradeEnabled", {
  # tests for the property `tradeEnabled` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tradeEnabled`, "EXPECTED_RESULT")
})

test_that("transferEnabled", {
  # tests for the property `transferEnabled` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`transferEnabled`, "EXPECTED_RESULT")
})

test_that("userAssets", {
  # tests for the property `userAssets` (array[InlineResponse20019UserAssets])

  # uncomment below to test the property
  #expect_equal(model.instance$`userAssets`, "EXPECTED_RESULT")
})

