# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SapiV1BswapLiquidityShare")

model.instance <- SapiV1BswapLiquidityShare$new()

test_that("shareAmount", {
  # tests for the property `shareAmount` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`shareAmount`, "EXPECTED_RESULT")
})

test_that("sharePercentage", {
  # tests for the property `sharePercentage` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`sharePercentage`, "EXPECTED_RESULT")
})

test_that("asset", {
  # tests for the property `asset` (SapiV1BswapLiquidityShareAsset)

  # uncomment below to test the property
  #expect_equal(model.instance$`asset`, "EXPECTED_RESULT")
})

