# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20057MarginTradeCoeffVo")

model.instance <- InlineResponse20057MarginTradeCoeffVo$new()

test_that("forceLiquidationBar", {
  # tests for the property `forceLiquidationBar` (character)
  # Liquidation margin ratio

  # uncomment below to test the property
  #expect_equal(model.instance$`forceLiquidationBar`, "EXPECTED_RESULT")
})

test_that("marginCallBar", {
  # tests for the property `marginCallBar` (character)
  # Margin call margin ratio

  # uncomment below to test the property
  #expect_equal(model.instance$`marginCallBar`, "EXPECTED_RESULT")
})

test_that("normalBar", {
  # tests for the property `normalBar` (character)
  # Initial margin ratio

  # uncomment below to test the property
  #expect_equal(model.instance$`normalBar`, "EXPECTED_RESULT")
})

