# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20059")

model.instance <- InlineResponse20059$new()

test_that("email", {
  # tests for the property `email` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("isFuturesEnabled", {
  # tests for the property `isFuturesEnabled` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isFuturesEnabled`, "EXPECTED_RESULT")
})

