# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20076")

model.instance <- InlineResponse20076$new()

test_that("purchaseId", {
  # tests for the property `purchaseId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`purchaseId`, "EXPECTED_RESULT")
})

