# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20082")

model.instance <- InlineResponse20082$new()

test_that("positionAmountVos", {
  # tests for the property `positionAmountVos` (array[InlineResponse20082PositionAmountVos])

  # uncomment below to test the property
  #expect_equal(model.instance$`positionAmountVos`, "EXPECTED_RESULT")
})

test_that("totalAmountInBTC", {
  # tests for the property `totalAmountInBTC` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalAmountInBTC`, "EXPECTED_RESULT")
})

test_that("totalAmountInUSDT", {
  # tests for the property `totalAmountInUSDT` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalAmountInUSDT`, "EXPECTED_RESULT")
})

test_that("totalFixedAmountInBTC", {
  # tests for the property `totalFixedAmountInBTC` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalFixedAmountInBTC`, "EXPECTED_RESULT")
})

test_that("totalFixedAmountInUSDT", {
  # tests for the property `totalFixedAmountInUSDT` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalFixedAmountInUSDT`, "EXPECTED_RESULT")
})

test_that("totalFlexibleInBTC", {
  # tests for the property `totalFlexibleInBTC` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalFlexibleInBTC`, "EXPECTED_RESULT")
})

test_that("totalFlexibleInUSDT", {
  # tests for the property `totalFlexibleInUSDT` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalFlexibleInUSDT`, "EXPECTED_RESULT")
})

