# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20094Data")

model.instance <- InlineResponse20094Data$new()

test_that("workerName", {
  # tests for the property `workerName` (character)
  # Mining Account name

  # uncomment below to test the property
  #expect_equal(model.instance$`workerName`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)
  # Type of hourly hashrate

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("hashrateDatas", {
  # tests for the property `hashrateDatas` (array[InlineResponse20094HashrateDatas])

  # uncomment below to test the property
  #expect_equal(model.instance$`hashrateDatas`, "EXPECTED_RESULT")
})

