# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse20083
#'
#' @description InlineResponse20083 Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field purchaseId  integer 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20083 <- R6::R6Class(
  'InlineResponse20083',
  public = list(
    `purchaseId` = NULL,
    initialize = function(
        `purchaseId`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`purchaseId`)) {
        stopifnot(is.numeric(`purchaseId`), length(`purchaseId`) == 1)
        self$`purchaseId` <- `purchaseId`
      }
    },
    toJSON = function() {
      InlineResponse20083Object <- list()
      if (!is.null(self$`purchaseId`)) {
        InlineResponse20083Object[['purchaseId']] <-
          self$`purchaseId`
      }

      InlineResponse20083Object
    },
    fromJSON = function(InlineResponse20083Json) {
      InlineResponse20083Object <- jsonlite::fromJSON(InlineResponse20083Json)
      if (!is.null(InlineResponse20083Object$`purchaseId`)) {
        self$`purchaseId` <- InlineResponse20083Object$`purchaseId`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`purchaseId`)) {
        sprintf(
        '"purchaseId":
          %d
                ',
        self$`purchaseId`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse20083Json) {
      InlineResponse20083Object <- jsonlite::fromJSON(InlineResponse20083Json)
      self$`purchaseId` <- InlineResponse20083Object$`purchaseId`
      self
    }
  )
)
