# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse200105
#'
#' @description InlineResponse200105 Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field operationId  integer 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse200105 <- R6::R6Class(
  'InlineResponse200105',
  public = list(
    `operationId` = NULL,
    initialize = function(
        `operationId`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`operationId`)) {
        stopifnot(is.numeric(`operationId`), length(`operationId`) == 1)
        self$`operationId` <- `operationId`
      }
    },
    toJSON = function() {
      InlineResponse200105Object <- list()
      if (!is.null(self$`operationId`)) {
        InlineResponse200105Object[['operationId']] <-
          self$`operationId`
      }

      InlineResponse200105Object
    },
    fromJSON = function(InlineResponse200105Json) {
      InlineResponse200105Object <- jsonlite::fromJSON(InlineResponse200105Json)
      if (!is.null(InlineResponse200105Object$`operationId`)) {
        self$`operationId` <- InlineResponse200105Object$`operationId`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`operationId`)) {
        sprintf(
        '"operationId":
          %d
                ',
        self$`operationId`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse200105Json) {
      InlineResponse200105Object <- jsonlite::fromJSON(InlineResponse200105Json)
      self$`operationId` <- InlineResponse200105Object$`operationId`
      self
    }
  )
)
