# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse20089PositionAmountVos
#'
#' @description InlineResponse20089PositionAmountVos Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field amount  character 
#'
#' @field amountInBTC  character 
#'
#' @field amountInUSDT  character 
#'
#' @field asset  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20089PositionAmountVos <- R6::R6Class(
  'InlineResponse20089PositionAmountVos',
  public = list(
    `amount` = NULL,
    `amountInBTC` = NULL,
    `amountInUSDT` = NULL,
    `asset` = NULL,
    initialize = function(
        `amount`, `amountInBTC`, `amountInUSDT`, `asset`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`amount`)) {
        stopifnot(is.character(`amount`), length(`amount`) == 1)
        self$`amount` <- `amount`
      }
      if (!missing(`amountInBTC`)) {
        stopifnot(is.character(`amountInBTC`), length(`amountInBTC`) == 1)
        self$`amountInBTC` <- `amountInBTC`
      }
      if (!missing(`amountInUSDT`)) {
        stopifnot(is.character(`amountInUSDT`), length(`amountInUSDT`) == 1)
        self$`amountInUSDT` <- `amountInUSDT`
      }
      if (!missing(`asset`)) {
        stopifnot(is.character(`asset`), length(`asset`) == 1)
        self$`asset` <- `asset`
      }
    },
    toJSON = function() {
      InlineResponse20089PositionAmountVosObject <- list()
      if (!is.null(self$`amount`)) {
        InlineResponse20089PositionAmountVosObject[['amount']] <-
          self$`amount`
      }
      if (!is.null(self$`amountInBTC`)) {
        InlineResponse20089PositionAmountVosObject[['amountInBTC']] <-
          self$`amountInBTC`
      }
      if (!is.null(self$`amountInUSDT`)) {
        InlineResponse20089PositionAmountVosObject[['amountInUSDT']] <-
          self$`amountInUSDT`
      }
      if (!is.null(self$`asset`)) {
        InlineResponse20089PositionAmountVosObject[['asset']] <-
          self$`asset`
      }

      InlineResponse20089PositionAmountVosObject
    },
    fromJSON = function(InlineResponse20089PositionAmountVosJson) {
      InlineResponse20089PositionAmountVosObject <- jsonlite::fromJSON(InlineResponse20089PositionAmountVosJson)
      if (!is.null(InlineResponse20089PositionAmountVosObject$`amount`)) {
        self$`amount` <- InlineResponse20089PositionAmountVosObject$`amount`
      }
      if (!is.null(InlineResponse20089PositionAmountVosObject$`amountInBTC`)) {
        self$`amountInBTC` <- InlineResponse20089PositionAmountVosObject$`amountInBTC`
      }
      if (!is.null(InlineResponse20089PositionAmountVosObject$`amountInUSDT`)) {
        self$`amountInUSDT` <- InlineResponse20089PositionAmountVosObject$`amountInUSDT`
      }
      if (!is.null(InlineResponse20089PositionAmountVosObject$`asset`)) {
        self$`asset` <- InlineResponse20089PositionAmountVosObject$`asset`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`amount`)) {
        sprintf(
        '"amount":
          "%s"
                ',
        self$`amount`
        )},
        if (!is.null(self$`amountInBTC`)) {
        sprintf(
        '"amountInBTC":
          "%s"
                ',
        self$`amountInBTC`
        )},
        if (!is.null(self$`amountInUSDT`)) {
        sprintf(
        '"amountInUSDT":
          "%s"
                ',
        self$`amountInUSDT`
        )},
        if (!is.null(self$`asset`)) {
        sprintf(
        '"asset":
          "%s"
                ',
        self$`asset`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse20089PositionAmountVosJson) {
      InlineResponse20089PositionAmountVosObject <- jsonlite::fromJSON(InlineResponse20089PositionAmountVosJson)
      self$`amount` <- InlineResponse20089PositionAmountVosObject$`amount`
      self$`amountInBTC` <- InlineResponse20089PositionAmountVosObject$`amountInBTC`
      self$`amountInUSDT` <- InlineResponse20089PositionAmountVosObject$`amountInUSDT`
      self$`asset` <- InlineResponse20089PositionAmountVosObject$`asset`
      self
    }
  )
)
