# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse20061SubAccountList
#'
#' @description InlineResponse20061SubAccountList Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field email  character 
#'
#' @field totalAssetOfBtc  character 
#'
#' @field totalLiabilityOfBtc  character 
#'
#' @field totalNetAssetOfBtc  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20061SubAccountList <- R6::R6Class(
  'InlineResponse20061SubAccountList',
  public = list(
    `email` = NULL,
    `totalAssetOfBtc` = NULL,
    `totalLiabilityOfBtc` = NULL,
    `totalNetAssetOfBtc` = NULL,
    initialize = function(
        `email`, `totalAssetOfBtc`, `totalLiabilityOfBtc`, `totalNetAssetOfBtc`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`email`)) {
        stopifnot(is.character(`email`), length(`email`) == 1)
        self$`email` <- `email`
      }
      if (!missing(`totalAssetOfBtc`)) {
        stopifnot(is.character(`totalAssetOfBtc`), length(`totalAssetOfBtc`) == 1)
        self$`totalAssetOfBtc` <- `totalAssetOfBtc`
      }
      if (!missing(`totalLiabilityOfBtc`)) {
        stopifnot(is.character(`totalLiabilityOfBtc`), length(`totalLiabilityOfBtc`) == 1)
        self$`totalLiabilityOfBtc` <- `totalLiabilityOfBtc`
      }
      if (!missing(`totalNetAssetOfBtc`)) {
        stopifnot(is.character(`totalNetAssetOfBtc`), length(`totalNetAssetOfBtc`) == 1)
        self$`totalNetAssetOfBtc` <- `totalNetAssetOfBtc`
      }
    },
    toJSON = function() {
      InlineResponse20061SubAccountListObject <- list()
      if (!is.null(self$`email`)) {
        InlineResponse20061SubAccountListObject[['email']] <-
          self$`email`
      }
      if (!is.null(self$`totalAssetOfBtc`)) {
        InlineResponse20061SubAccountListObject[['totalAssetOfBtc']] <-
          self$`totalAssetOfBtc`
      }
      if (!is.null(self$`totalLiabilityOfBtc`)) {
        InlineResponse20061SubAccountListObject[['totalLiabilityOfBtc']] <-
          self$`totalLiabilityOfBtc`
      }
      if (!is.null(self$`totalNetAssetOfBtc`)) {
        InlineResponse20061SubAccountListObject[['totalNetAssetOfBtc']] <-
          self$`totalNetAssetOfBtc`
      }

      InlineResponse20061SubAccountListObject
    },
    fromJSON = function(InlineResponse20061SubAccountListJson) {
      InlineResponse20061SubAccountListObject <- jsonlite::fromJSON(InlineResponse20061SubAccountListJson)
      if (!is.null(InlineResponse20061SubAccountListObject$`email`)) {
        self$`email` <- InlineResponse20061SubAccountListObject$`email`
      }
      if (!is.null(InlineResponse20061SubAccountListObject$`totalAssetOfBtc`)) {
        self$`totalAssetOfBtc` <- InlineResponse20061SubAccountListObject$`totalAssetOfBtc`
      }
      if (!is.null(InlineResponse20061SubAccountListObject$`totalLiabilityOfBtc`)) {
        self$`totalLiabilityOfBtc` <- InlineResponse20061SubAccountListObject$`totalLiabilityOfBtc`
      }
      if (!is.null(InlineResponse20061SubAccountListObject$`totalNetAssetOfBtc`)) {
        self$`totalNetAssetOfBtc` <- InlineResponse20061SubAccountListObject$`totalNetAssetOfBtc`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`email`)) {
        sprintf(
        '"email":
          "%s"
                ',
        self$`email`
        )},
        if (!is.null(self$`totalAssetOfBtc`)) {
        sprintf(
        '"totalAssetOfBtc":
          "%s"
                ',
        self$`totalAssetOfBtc`
        )},
        if (!is.null(self$`totalLiabilityOfBtc`)) {
        sprintf(
        '"totalLiabilityOfBtc":
          "%s"
                ',
        self$`totalLiabilityOfBtc`
        )},
        if (!is.null(self$`totalNetAssetOfBtc`)) {
        sprintf(
        '"totalNetAssetOfBtc":
          "%s"
                ',
        self$`totalNetAssetOfBtc`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse20061SubAccountListJson) {
      InlineResponse20061SubAccountListObject <- jsonlite::fromJSON(InlineResponse20061SubAccountListJson)
      self$`email` <- InlineResponse20061SubAccountListObject$`email`
      self$`totalAssetOfBtc` <- InlineResponse20061SubAccountListObject$`totalAssetOfBtc`
      self$`totalLiabilityOfBtc` <- InlineResponse20061SubAccountListObject$`totalLiabilityOfBtc`
      self$`totalNetAssetOfBtc` <- InlineResponse20061SubAccountListObject$`totalNetAssetOfBtc`
      self
    }
  )
)
