# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse20042
#'
#' @description InlineResponse20042 Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field total  integer 
#'
#' @field rows  list( \link{InlineResponse20042Rows} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20042 <- R6::R6Class(
  'InlineResponse20042',
  public = list(
    `total` = NULL,
    `rows` = NULL,
    initialize = function(
        `total`, `rows`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`total`)) {
        stopifnot(is.numeric(`total`), length(`total`) == 1)
        self$`total` <- `total`
      }
      if (!missing(`rows`)) {
        stopifnot(is.vector(`rows`), length(`rows`) != 0)
        sapply(`rows`, function(x) stopifnot(R6::is.R6(x)))
        self$`rows` <- `rows`
      }
    },
    toJSON = function() {
      InlineResponse20042Object <- list()
      if (!is.null(self$`total`)) {
        InlineResponse20042Object[['total']] <-
          self$`total`
      }
      if (!is.null(self$`rows`)) {
        InlineResponse20042Object[['rows']] <-
          lapply(self$`rows`, function(x) x$toJSON())
      }

      InlineResponse20042Object
    },
    fromJSON = function(InlineResponse20042Json) {
      InlineResponse20042Object <- jsonlite::fromJSON(InlineResponse20042Json)
      if (!is.null(InlineResponse20042Object$`total`)) {
        self$`total` <- InlineResponse20042Object$`total`
      }
      if (!is.null(InlineResponse20042Object$`rows`)) {
        self$`rows` <- ApiClient$new()$deserializeObj(InlineResponse20042Object$`rows`, "array[InlineResponse20042Rows]", loadNamespace("binanceRapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`total`)) {
        sprintf(
        '"total":
          %d
                ',
        self$`total`
        )},
        if (!is.null(self$`rows`)) {
        sprintf(
        '"rows":
        [%s]
',
        paste(sapply(self$`rows`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse20042Json) {
      InlineResponse20042Object <- jsonlite::fromJSON(InlineResponse20042Json)
      self$`total` <- InlineResponse20042Object$`total`
      self$`rows` <- ApiClient$new()$deserializeObj(InlineResponse20042Object$`rows`, "array[InlineResponse20042Rows]", loadNamespace("binanceRapi"))
      self
    }
  )
)
