# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse200102
#'
#' @description InlineResponse200102 Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field tokenName  character 
#'
#' @field userDailyTotalPurchaseLimit  character 
#'
#' @field userDailyTotalRedeemLimit  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse200102 <- R6::R6Class(
  'InlineResponse200102',
  public = list(
    `tokenName` = NULL,
    `userDailyTotalPurchaseLimit` = NULL,
    `userDailyTotalRedeemLimit` = NULL,
    initialize = function(
        `tokenName`, `userDailyTotalPurchaseLimit`, `userDailyTotalRedeemLimit`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`tokenName`)) {
        stopifnot(is.character(`tokenName`), length(`tokenName`) == 1)
        self$`tokenName` <- `tokenName`
      }
      if (!missing(`userDailyTotalPurchaseLimit`)) {
        stopifnot(is.character(`userDailyTotalPurchaseLimit`), length(`userDailyTotalPurchaseLimit`) == 1)
        self$`userDailyTotalPurchaseLimit` <- `userDailyTotalPurchaseLimit`
      }
      if (!missing(`userDailyTotalRedeemLimit`)) {
        stopifnot(is.character(`userDailyTotalRedeemLimit`), length(`userDailyTotalRedeemLimit`) == 1)
        self$`userDailyTotalRedeemLimit` <- `userDailyTotalRedeemLimit`
      }
    },
    toJSON = function() {
      InlineResponse200102Object <- list()
      if (!is.null(self$`tokenName`)) {
        InlineResponse200102Object[['tokenName']] <-
          self$`tokenName`
      }
      if (!is.null(self$`userDailyTotalPurchaseLimit`)) {
        InlineResponse200102Object[['userDailyTotalPurchaseLimit']] <-
          self$`userDailyTotalPurchaseLimit`
      }
      if (!is.null(self$`userDailyTotalRedeemLimit`)) {
        InlineResponse200102Object[['userDailyTotalRedeemLimit']] <-
          self$`userDailyTotalRedeemLimit`
      }

      InlineResponse200102Object
    },
    fromJSON = function(InlineResponse200102Json) {
      InlineResponse200102Object <- jsonlite::fromJSON(InlineResponse200102Json)
      if (!is.null(InlineResponse200102Object$`tokenName`)) {
        self$`tokenName` <- InlineResponse200102Object$`tokenName`
      }
      if (!is.null(InlineResponse200102Object$`userDailyTotalPurchaseLimit`)) {
        self$`userDailyTotalPurchaseLimit` <- InlineResponse200102Object$`userDailyTotalPurchaseLimit`
      }
      if (!is.null(InlineResponse200102Object$`userDailyTotalRedeemLimit`)) {
        self$`userDailyTotalRedeemLimit` <- InlineResponse200102Object$`userDailyTotalRedeemLimit`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`tokenName`)) {
        sprintf(
        '"tokenName":
          "%s"
                ',
        self$`tokenName`
        )},
        if (!is.null(self$`userDailyTotalPurchaseLimit`)) {
        sprintf(
        '"userDailyTotalPurchaseLimit":
          "%s"
                ',
        self$`userDailyTotalPurchaseLimit`
        )},
        if (!is.null(self$`userDailyTotalRedeemLimit`)) {
        sprintf(
        '"userDailyTotalRedeemLimit":
          "%s"
                ',
        self$`userDailyTotalRedeemLimit`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse200102Json) {
      InlineResponse200102Object <- jsonlite::fromJSON(InlineResponse200102Json)
      self$`tokenName` <- InlineResponse200102Object$`tokenName`
      self$`userDailyTotalPurchaseLimit` <- InlineResponse200102Object$`userDailyTotalPurchaseLimit`
      self$`userDailyTotalRedeemLimit` <- InlineResponse200102Object$`userDailyTotalRedeemLimit`
      self
    }
  )
)
