# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse20087HashrateDatas
#'
#' @description InlineResponse20087HashrateDatas Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field time  integer 
#'
#' @field hashrate  character 
#'
#' @field reject  integer 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20087HashrateDatas <- R6::R6Class(
  'InlineResponse20087HashrateDatas',
  public = list(
    `time` = NULL,
    `hashrate` = NULL,
    `reject` = NULL,
    initialize = function(
        `time`, `hashrate`, `reject`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`time`)) {
        stopifnot(is.numeric(`time`), length(`time`) == 1)
        self$`time` <- `time`
      }
      if (!missing(`hashrate`)) {
        stopifnot(is.character(`hashrate`), length(`hashrate`) == 1)
        self$`hashrate` <- `hashrate`
      }
      if (!missing(`reject`)) {
        stopifnot(is.numeric(`reject`), length(`reject`) == 1)
        self$`reject` <- `reject`
      }
    },
    toJSON = function() {
      InlineResponse20087HashrateDatasObject <- list()
      if (!is.null(self$`time`)) {
        InlineResponse20087HashrateDatasObject[['time']] <-
          self$`time`
      }
      if (!is.null(self$`hashrate`)) {
        InlineResponse20087HashrateDatasObject[['hashrate']] <-
          self$`hashrate`
      }
      if (!is.null(self$`reject`)) {
        InlineResponse20087HashrateDatasObject[['reject']] <-
          self$`reject`
      }

      InlineResponse20087HashrateDatasObject
    },
    fromJSON = function(InlineResponse20087HashrateDatasJson) {
      InlineResponse20087HashrateDatasObject <- jsonlite::fromJSON(InlineResponse20087HashrateDatasJson)
      if (!is.null(InlineResponse20087HashrateDatasObject$`time`)) {
        self$`time` <- InlineResponse20087HashrateDatasObject$`time`
      }
      if (!is.null(InlineResponse20087HashrateDatasObject$`hashrate`)) {
        self$`hashrate` <- InlineResponse20087HashrateDatasObject$`hashrate`
      }
      if (!is.null(InlineResponse20087HashrateDatasObject$`reject`)) {
        self$`reject` <- InlineResponse20087HashrateDatasObject$`reject`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`time`)) {
        sprintf(
        '"time":
          %d
                ',
        self$`time`
        )},
        if (!is.null(self$`hashrate`)) {
        sprintf(
        '"hashrate":
          "%s"
                ',
        self$`hashrate`
        )},
        if (!is.null(self$`reject`)) {
        sprintf(
        '"reject":
          %d
                ',
        self$`reject`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse20087HashrateDatasJson) {
      InlineResponse20087HashrateDatasObject <- jsonlite::fromJSON(InlineResponse20087HashrateDatasJson)
      self$`time` <- InlineResponse20087HashrateDatasObject$`time`
      self$`hashrate` <- InlineResponse20087HashrateDatasObject$`hashrate`
      self$`reject` <- InlineResponse20087HashrateDatasObject$`reject`
      self
    }
  )
)
