# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse20010Rows
#'
#' @description InlineResponse20010Rows Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field isolatedSymbol  character 
#'
#' @field txId  integer 
#'
#' @field asset  character 
#'
#' @field principal  character 
#'
#' @field timestamp  integer 
#'
#' @field status  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20010Rows <- R6::R6Class(
  'InlineResponse20010Rows',
  public = list(
    `isolatedSymbol` = NULL,
    `txId` = NULL,
    `asset` = NULL,
    `principal` = NULL,
    `timestamp` = NULL,
    `status` = NULL,
    initialize = function(
        `isolatedSymbol`, `txId`, `asset`, `principal`, `timestamp`, `status`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`isolatedSymbol`)) {
        stopifnot(is.character(`isolatedSymbol`), length(`isolatedSymbol`) == 1)
        self$`isolatedSymbol` <- `isolatedSymbol`
      }
      if (!missing(`txId`)) {
        stopifnot(is.numeric(`txId`), length(`txId`) == 1)
        self$`txId` <- `txId`
      }
      if (!missing(`asset`)) {
        stopifnot(is.character(`asset`), length(`asset`) == 1)
        self$`asset` <- `asset`
      }
      if (!missing(`principal`)) {
        stopifnot(is.character(`principal`), length(`principal`) == 1)
        self$`principal` <- `principal`
      }
      if (!missing(`timestamp`)) {
        stopifnot(is.numeric(`timestamp`), length(`timestamp`) == 1)
        self$`timestamp` <- `timestamp`
      }
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
    },
    toJSON = function() {
      InlineResponse20010RowsObject <- list()
      if (!is.null(self$`isolatedSymbol`)) {
        InlineResponse20010RowsObject[['isolatedSymbol']] <-
          self$`isolatedSymbol`
      }
      if (!is.null(self$`txId`)) {
        InlineResponse20010RowsObject[['txId']] <-
          self$`txId`
      }
      if (!is.null(self$`asset`)) {
        InlineResponse20010RowsObject[['asset']] <-
          self$`asset`
      }
      if (!is.null(self$`principal`)) {
        InlineResponse20010RowsObject[['principal']] <-
          self$`principal`
      }
      if (!is.null(self$`timestamp`)) {
        InlineResponse20010RowsObject[['timestamp']] <-
          self$`timestamp`
      }
      if (!is.null(self$`status`)) {
        InlineResponse20010RowsObject[['status']] <-
          self$`status`
      }

      InlineResponse20010RowsObject
    },
    fromJSON = function(InlineResponse20010RowsJson) {
      InlineResponse20010RowsObject <- jsonlite::fromJSON(InlineResponse20010RowsJson)
      if (!is.null(InlineResponse20010RowsObject$`isolatedSymbol`)) {
        self$`isolatedSymbol` <- InlineResponse20010RowsObject$`isolatedSymbol`
      }
      if (!is.null(InlineResponse20010RowsObject$`txId`)) {
        self$`txId` <- InlineResponse20010RowsObject$`txId`
      }
      if (!is.null(InlineResponse20010RowsObject$`asset`)) {
        self$`asset` <- InlineResponse20010RowsObject$`asset`
      }
      if (!is.null(InlineResponse20010RowsObject$`principal`)) {
        self$`principal` <- InlineResponse20010RowsObject$`principal`
      }
      if (!is.null(InlineResponse20010RowsObject$`timestamp`)) {
        self$`timestamp` <- InlineResponse20010RowsObject$`timestamp`
      }
      if (!is.null(InlineResponse20010RowsObject$`status`)) {
        self$`status` <- InlineResponse20010RowsObject$`status`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`isolatedSymbol`)) {
        sprintf(
        '"isolatedSymbol":
          "%s"
                ',
        self$`isolatedSymbol`
        )},
        if (!is.null(self$`txId`)) {
        sprintf(
        '"txId":
          %d
                ',
        self$`txId`
        )},
        if (!is.null(self$`asset`)) {
        sprintf(
        '"asset":
          "%s"
                ',
        self$`asset`
        )},
        if (!is.null(self$`principal`)) {
        sprintf(
        '"principal":
          "%s"
                ',
        self$`principal`
        )},
        if (!is.null(self$`timestamp`)) {
        sprintf(
        '"timestamp":
          %d
                ',
        self$`timestamp`
        )},
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
          "%s"
                ',
        self$`status`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse20010RowsJson) {
      InlineResponse20010RowsObject <- jsonlite::fromJSON(InlineResponse20010RowsJson)
      self$`isolatedSymbol` <- InlineResponse20010RowsObject$`isolatedSymbol`
      self$`txId` <- InlineResponse20010RowsObject$`txId`
      self$`asset` <- InlineResponse20010RowsObject$`asset`
      self$`principal` <- InlineResponse20010RowsObject$`principal`
      self$`timestamp` <- InlineResponse20010RowsObject$`timestamp`
      self$`status` <- InlineResponse20010RowsObject$`status`
      self
    }
  )
)
