# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse20038
#'
#' @description InlineResponse20038 Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field totalServiceCharge  character 
#'
#' @field totalTransfered  character 
#'
#' @field transferResult  list( \link{InlineResponse20038TransferResult} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20038 <- R6::R6Class(
  'InlineResponse20038',
  public = list(
    `totalServiceCharge` = NULL,
    `totalTransfered` = NULL,
    `transferResult` = NULL,
    initialize = function(
        `totalServiceCharge`, `totalTransfered`, `transferResult`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`totalServiceCharge`)) {
        stopifnot(is.character(`totalServiceCharge`), length(`totalServiceCharge`) == 1)
        self$`totalServiceCharge` <- `totalServiceCharge`
      }
      if (!missing(`totalTransfered`)) {
        stopifnot(is.character(`totalTransfered`), length(`totalTransfered`) == 1)
        self$`totalTransfered` <- `totalTransfered`
      }
      if (!missing(`transferResult`)) {
        stopifnot(is.vector(`transferResult`), length(`transferResult`) != 0)
        sapply(`transferResult`, function(x) stopifnot(R6::is.R6(x)))
        self$`transferResult` <- `transferResult`
      }
    },
    toJSON = function() {
      InlineResponse20038Object <- list()
      if (!is.null(self$`totalServiceCharge`)) {
        InlineResponse20038Object[['totalServiceCharge']] <-
          self$`totalServiceCharge`
      }
      if (!is.null(self$`totalTransfered`)) {
        InlineResponse20038Object[['totalTransfered']] <-
          self$`totalTransfered`
      }
      if (!is.null(self$`transferResult`)) {
        InlineResponse20038Object[['transferResult']] <-
          lapply(self$`transferResult`, function(x) x$toJSON())
      }

      InlineResponse20038Object
    },
    fromJSON = function(InlineResponse20038Json) {
      InlineResponse20038Object <- jsonlite::fromJSON(InlineResponse20038Json)
      if (!is.null(InlineResponse20038Object$`totalServiceCharge`)) {
        self$`totalServiceCharge` <- InlineResponse20038Object$`totalServiceCharge`
      }
      if (!is.null(InlineResponse20038Object$`totalTransfered`)) {
        self$`totalTransfered` <- InlineResponse20038Object$`totalTransfered`
      }
      if (!is.null(InlineResponse20038Object$`transferResult`)) {
        self$`transferResult` <- ApiClient$new()$deserializeObj(InlineResponse20038Object$`transferResult`, "array[InlineResponse20038TransferResult]", loadNamespace("binanceRapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`totalServiceCharge`)) {
        sprintf(
        '"totalServiceCharge":
          "%s"
                ',
        self$`totalServiceCharge`
        )},
        if (!is.null(self$`totalTransfered`)) {
        sprintf(
        '"totalTransfered":
          "%s"
                ',
        self$`totalTransfered`
        )},
        if (!is.null(self$`transferResult`)) {
        sprintf(
        '"transferResult":
        [%s]
',
        paste(sapply(self$`transferResult`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse20038Json) {
      InlineResponse20038Object <- jsonlite::fromJSON(InlineResponse20038Json)
      self$`totalServiceCharge` <- InlineResponse20038Object$`totalServiceCharge`
      self$`totalTransfered` <- InlineResponse20038Object$`totalTransfered`
      self$`transferResult` <- ApiClient$new()$deserializeObj(InlineResponse20038Object$`transferResult`, "array[InlineResponse20038TransferResult]", loadNamespace("binanceRapi"))
      self
    }
  )
)
