# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse20043
#'
#' @description InlineResponse20043 Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field tranId  integer 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20043 <- R6::R6Class(
  'InlineResponse20043',
  public = list(
    `tranId` = NULL,
    initialize = function(
        `tranId`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`tranId`)) {
        stopifnot(is.numeric(`tranId`), length(`tranId`) == 1)
        self$`tranId` <- `tranId`
      }
    },
    toJSON = function() {
      InlineResponse20043Object <- list()
      if (!is.null(self$`tranId`)) {
        InlineResponse20043Object[['tranId']] <-
          self$`tranId`
      }

      InlineResponse20043Object
    },
    fromJSON = function(InlineResponse20043Json) {
      InlineResponse20043Object <- jsonlite::fromJSON(InlineResponse20043Json)
      if (!is.null(InlineResponse20043Object$`tranId`)) {
        self$`tranId` <- InlineResponse20043Object$`tranId`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`tranId`)) {
        sprintf(
        '"tranId":
          %d
                ',
        self$`tranId`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse20043Json) {
      InlineResponse20043Object <- jsonlite::fromJSON(InlineResponse20043Json)
      self$`tranId` <- InlineResponse20043Object$`tranId`
      self
    }
  )
)
