# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse20040CTR
#'
#' @description InlineResponse20040CTR Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field minWithdrawAmount  character 
#'
#' @field depositStatus  character 
#'
#' @field withdrawFee  integer 
#'
#' @field withdrawStatus  character 
#'
#' @field depositTip  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20040CTR <- R6::R6Class(
  'InlineResponse20040CTR',
  public = list(
    `minWithdrawAmount` = NULL,
    `depositStatus` = NULL,
    `withdrawFee` = NULL,
    `withdrawStatus` = NULL,
    `depositTip` = NULL,
    initialize = function(
        `minWithdrawAmount`, `depositStatus`, `withdrawFee`, `withdrawStatus`, `depositTip`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`minWithdrawAmount`)) {
        stopifnot(is.character(`minWithdrawAmount`), length(`minWithdrawAmount`) == 1)
        self$`minWithdrawAmount` <- `minWithdrawAmount`
      }
      if (!missing(`depositStatus`)) {
        stopifnot(is.logical(`depositStatus`), length(`depositStatus`) == 1)
        self$`depositStatus` <- `depositStatus`
      }
      if (!missing(`withdrawFee`)) {
        stopifnot(is.numeric(`withdrawFee`), length(`withdrawFee`) == 1)
        self$`withdrawFee` <- `withdrawFee`
      }
      if (!missing(`withdrawStatus`)) {
        stopifnot(is.logical(`withdrawStatus`), length(`withdrawStatus`) == 1)
        self$`withdrawStatus` <- `withdrawStatus`
      }
      if (!missing(`depositTip`)) {
        stopifnot(is.character(`depositTip`), length(`depositTip`) == 1)
        self$`depositTip` <- `depositTip`
      }
    },
    toJSON = function() {
      InlineResponse20040CTRObject <- list()
      if (!is.null(self$`minWithdrawAmount`)) {
        InlineResponse20040CTRObject[['minWithdrawAmount']] <-
          self$`minWithdrawAmount`
      }
      if (!is.null(self$`depositStatus`)) {
        InlineResponse20040CTRObject[['depositStatus']] <-
          self$`depositStatus`
      }
      if (!is.null(self$`withdrawFee`)) {
        InlineResponse20040CTRObject[['withdrawFee']] <-
          self$`withdrawFee`
      }
      if (!is.null(self$`withdrawStatus`)) {
        InlineResponse20040CTRObject[['withdrawStatus']] <-
          self$`withdrawStatus`
      }
      if (!is.null(self$`depositTip`)) {
        InlineResponse20040CTRObject[['depositTip']] <-
          self$`depositTip`
      }

      InlineResponse20040CTRObject
    },
    fromJSON = function(InlineResponse20040CTRJson) {
      InlineResponse20040CTRObject <- jsonlite::fromJSON(InlineResponse20040CTRJson)
      if (!is.null(InlineResponse20040CTRObject$`minWithdrawAmount`)) {
        self$`minWithdrawAmount` <- InlineResponse20040CTRObject$`minWithdrawAmount`
      }
      if (!is.null(InlineResponse20040CTRObject$`depositStatus`)) {
        self$`depositStatus` <- InlineResponse20040CTRObject$`depositStatus`
      }
      if (!is.null(InlineResponse20040CTRObject$`withdrawFee`)) {
        self$`withdrawFee` <- InlineResponse20040CTRObject$`withdrawFee`
      }
      if (!is.null(InlineResponse20040CTRObject$`withdrawStatus`)) {
        self$`withdrawStatus` <- InlineResponse20040CTRObject$`withdrawStatus`
      }
      if (!is.null(InlineResponse20040CTRObject$`depositTip`)) {
        self$`depositTip` <- InlineResponse20040CTRObject$`depositTip`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`minWithdrawAmount`)) {
        sprintf(
        '"minWithdrawAmount":
          "%s"
                ',
        self$`minWithdrawAmount`
        )},
        if (!is.null(self$`depositStatus`)) {
        sprintf(
        '"depositStatus":
          %s
                ',
        tolower(self$`depositStatus`)
        )},
        if (!is.null(self$`withdrawFee`)) {
        sprintf(
        '"withdrawFee":
          %d
                ',
        self$`withdrawFee`
        )},
        if (!is.null(self$`withdrawStatus`)) {
        sprintf(
        '"withdrawStatus":
          %s
                ',
        tolower(self$`withdrawStatus`)
        )},
        if (!is.null(self$`depositTip`)) {
        sprintf(
        '"depositTip":
          "%s"
                ',
        self$`depositTip`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse20040CTRJson) {
      InlineResponse20040CTRObject <- jsonlite::fromJSON(InlineResponse20040CTRJson)
      self$`minWithdrawAmount` <- InlineResponse20040CTRObject$`minWithdrawAmount`
      self$`depositStatus` <- InlineResponse20040CTRObject$`depositStatus`
      self$`withdrawFee` <- InlineResponse20040CTRObject$`withdrawFee`
      self$`withdrawStatus` <- InlineResponse20040CTRObject$`withdrawStatus`
      self$`depositTip` <- InlineResponse20040CTRObject$`depositTip`
      self
    }
  )
)
