# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse20081
#'
#' @description InlineResponse20081 Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field asset  character 
#'
#' @field canTransfer  character 
#'
#' @field createTimestamp  integer 
#'
#' @field duration  integer 
#'
#' @field endTime  integer 
#'
#' @field interest  character 
#'
#' @field interestRate  character 
#'
#' @field lot  integer 
#'
#' @field positionId  integer 
#'
#' @field principal  character 
#'
#' @field projectId  character 
#'
#' @field projectName  character 
#'
#' @field purchaseTime  integer 
#'
#' @field redeemDate  character 
#'
#' @field startTime  integer 
#'
#' @field status  character 
#'
#' @field type  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20081 <- R6::R6Class(
  'InlineResponse20081',
  public = list(
    `asset` = NULL,
    `canTransfer` = NULL,
    `createTimestamp` = NULL,
    `duration` = NULL,
    `endTime` = NULL,
    `interest` = NULL,
    `interestRate` = NULL,
    `lot` = NULL,
    `positionId` = NULL,
    `principal` = NULL,
    `projectId` = NULL,
    `projectName` = NULL,
    `purchaseTime` = NULL,
    `redeemDate` = NULL,
    `startTime` = NULL,
    `status` = NULL,
    `type` = NULL,
    initialize = function(
        `asset`, `canTransfer`, `createTimestamp`, `duration`, `endTime`, `interest`, `interestRate`, `lot`, `positionId`, `principal`, `projectId`, `projectName`, `purchaseTime`, `redeemDate`, `startTime`, `status`, `type`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`asset`)) {
        stopifnot(is.character(`asset`), length(`asset`) == 1)
        self$`asset` <- `asset`
      }
      if (!missing(`canTransfer`)) {
        stopifnot(is.logical(`canTransfer`), length(`canTransfer`) == 1)
        self$`canTransfer` <- `canTransfer`
      }
      if (!missing(`createTimestamp`)) {
        stopifnot(is.numeric(`createTimestamp`), length(`createTimestamp`) == 1)
        self$`createTimestamp` <- `createTimestamp`
      }
      if (!missing(`duration`)) {
        stopifnot(is.numeric(`duration`), length(`duration`) == 1)
        self$`duration` <- `duration`
      }
      if (!missing(`endTime`)) {
        stopifnot(is.numeric(`endTime`), length(`endTime`) == 1)
        self$`endTime` <- `endTime`
      }
      if (!missing(`interest`)) {
        stopifnot(is.character(`interest`), length(`interest`) == 1)
        self$`interest` <- `interest`
      }
      if (!missing(`interestRate`)) {
        stopifnot(is.character(`interestRate`), length(`interestRate`) == 1)
        self$`interestRate` <- `interestRate`
      }
      if (!missing(`lot`)) {
        stopifnot(is.numeric(`lot`), length(`lot`) == 1)
        self$`lot` <- `lot`
      }
      if (!missing(`positionId`)) {
        stopifnot(is.numeric(`positionId`), length(`positionId`) == 1)
        self$`positionId` <- `positionId`
      }
      if (!missing(`principal`)) {
        stopifnot(is.character(`principal`), length(`principal`) == 1)
        self$`principal` <- `principal`
      }
      if (!missing(`projectId`)) {
        stopifnot(is.character(`projectId`), length(`projectId`) == 1)
        self$`projectId` <- `projectId`
      }
      if (!missing(`projectName`)) {
        stopifnot(is.character(`projectName`), length(`projectName`) == 1)
        self$`projectName` <- `projectName`
      }
      if (!missing(`purchaseTime`)) {
        stopifnot(is.numeric(`purchaseTime`), length(`purchaseTime`) == 1)
        self$`purchaseTime` <- `purchaseTime`
      }
      if (!missing(`redeemDate`)) {
        stopifnot(is.character(`redeemDate`), length(`redeemDate`) == 1)
        self$`redeemDate` <- `redeemDate`
      }
      if (!missing(`startTime`)) {
        stopifnot(is.numeric(`startTime`), length(`startTime`) == 1)
        self$`startTime` <- `startTime`
      }
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
    },
    toJSON = function() {
      InlineResponse20081Object <- list()
      if (!is.null(self$`asset`)) {
        InlineResponse20081Object[['asset']] <-
          self$`asset`
      }
      if (!is.null(self$`canTransfer`)) {
        InlineResponse20081Object[['canTransfer']] <-
          self$`canTransfer`
      }
      if (!is.null(self$`createTimestamp`)) {
        InlineResponse20081Object[['createTimestamp']] <-
          self$`createTimestamp`
      }
      if (!is.null(self$`duration`)) {
        InlineResponse20081Object[['duration']] <-
          self$`duration`
      }
      if (!is.null(self$`endTime`)) {
        InlineResponse20081Object[['endTime']] <-
          self$`endTime`
      }
      if (!is.null(self$`interest`)) {
        InlineResponse20081Object[['interest']] <-
          self$`interest`
      }
      if (!is.null(self$`interestRate`)) {
        InlineResponse20081Object[['interestRate']] <-
          self$`interestRate`
      }
      if (!is.null(self$`lot`)) {
        InlineResponse20081Object[['lot']] <-
          self$`lot`
      }
      if (!is.null(self$`positionId`)) {
        InlineResponse20081Object[['positionId']] <-
          self$`positionId`
      }
      if (!is.null(self$`principal`)) {
        InlineResponse20081Object[['principal']] <-
          self$`principal`
      }
      if (!is.null(self$`projectId`)) {
        InlineResponse20081Object[['projectId']] <-
          self$`projectId`
      }
      if (!is.null(self$`projectName`)) {
        InlineResponse20081Object[['projectName']] <-
          self$`projectName`
      }
      if (!is.null(self$`purchaseTime`)) {
        InlineResponse20081Object[['purchaseTime']] <-
          self$`purchaseTime`
      }
      if (!is.null(self$`redeemDate`)) {
        InlineResponse20081Object[['redeemDate']] <-
          self$`redeemDate`
      }
      if (!is.null(self$`startTime`)) {
        InlineResponse20081Object[['startTime']] <-
          self$`startTime`
      }
      if (!is.null(self$`status`)) {
        InlineResponse20081Object[['status']] <-
          self$`status`
      }
      if (!is.null(self$`type`)) {
        InlineResponse20081Object[['type']] <-
          self$`type`
      }

      InlineResponse20081Object
    },
    fromJSON = function(InlineResponse20081Json) {
      InlineResponse20081Object <- jsonlite::fromJSON(InlineResponse20081Json)
      if (!is.null(InlineResponse20081Object$`asset`)) {
        self$`asset` <- InlineResponse20081Object$`asset`
      }
      if (!is.null(InlineResponse20081Object$`canTransfer`)) {
        self$`canTransfer` <- InlineResponse20081Object$`canTransfer`
      }
      if (!is.null(InlineResponse20081Object$`createTimestamp`)) {
        self$`createTimestamp` <- InlineResponse20081Object$`createTimestamp`
      }
      if (!is.null(InlineResponse20081Object$`duration`)) {
        self$`duration` <- InlineResponse20081Object$`duration`
      }
      if (!is.null(InlineResponse20081Object$`endTime`)) {
        self$`endTime` <- InlineResponse20081Object$`endTime`
      }
      if (!is.null(InlineResponse20081Object$`interest`)) {
        self$`interest` <- InlineResponse20081Object$`interest`
      }
      if (!is.null(InlineResponse20081Object$`interestRate`)) {
        self$`interestRate` <- InlineResponse20081Object$`interestRate`
      }
      if (!is.null(InlineResponse20081Object$`lot`)) {
        self$`lot` <- InlineResponse20081Object$`lot`
      }
      if (!is.null(InlineResponse20081Object$`positionId`)) {
        self$`positionId` <- InlineResponse20081Object$`positionId`
      }
      if (!is.null(InlineResponse20081Object$`principal`)) {
        self$`principal` <- InlineResponse20081Object$`principal`
      }
      if (!is.null(InlineResponse20081Object$`projectId`)) {
        self$`projectId` <- InlineResponse20081Object$`projectId`
      }
      if (!is.null(InlineResponse20081Object$`projectName`)) {
        self$`projectName` <- InlineResponse20081Object$`projectName`
      }
      if (!is.null(InlineResponse20081Object$`purchaseTime`)) {
        self$`purchaseTime` <- InlineResponse20081Object$`purchaseTime`
      }
      if (!is.null(InlineResponse20081Object$`redeemDate`)) {
        self$`redeemDate` <- InlineResponse20081Object$`redeemDate`
      }
      if (!is.null(InlineResponse20081Object$`startTime`)) {
        self$`startTime` <- InlineResponse20081Object$`startTime`
      }
      if (!is.null(InlineResponse20081Object$`status`)) {
        self$`status` <- InlineResponse20081Object$`status`
      }
      if (!is.null(InlineResponse20081Object$`type`)) {
        self$`type` <- InlineResponse20081Object$`type`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`asset`)) {
        sprintf(
        '"asset":
          "%s"
                ',
        self$`asset`
        )},
        if (!is.null(self$`canTransfer`)) {
        sprintf(
        '"canTransfer":
          %s
                ',
        tolower(self$`canTransfer`)
        )},
        if (!is.null(self$`createTimestamp`)) {
        sprintf(
        '"createTimestamp":
          %d
                ',
        self$`createTimestamp`
        )},
        if (!is.null(self$`duration`)) {
        sprintf(
        '"duration":
          %d
                ',
        self$`duration`
        )},
        if (!is.null(self$`endTime`)) {
        sprintf(
        '"endTime":
          %d
                ',
        self$`endTime`
        )},
        if (!is.null(self$`interest`)) {
        sprintf(
        '"interest":
          "%s"
                ',
        self$`interest`
        )},
        if (!is.null(self$`interestRate`)) {
        sprintf(
        '"interestRate":
          "%s"
                ',
        self$`interestRate`
        )},
        if (!is.null(self$`lot`)) {
        sprintf(
        '"lot":
          %d
                ',
        self$`lot`
        )},
        if (!is.null(self$`positionId`)) {
        sprintf(
        '"positionId":
          %d
                ',
        self$`positionId`
        )},
        if (!is.null(self$`principal`)) {
        sprintf(
        '"principal":
          "%s"
                ',
        self$`principal`
        )},
        if (!is.null(self$`projectId`)) {
        sprintf(
        '"projectId":
          "%s"
                ',
        self$`projectId`
        )},
        if (!is.null(self$`projectName`)) {
        sprintf(
        '"projectName":
          "%s"
                ',
        self$`projectName`
        )},
        if (!is.null(self$`purchaseTime`)) {
        sprintf(
        '"purchaseTime":
          %d
                ',
        self$`purchaseTime`
        )},
        if (!is.null(self$`redeemDate`)) {
        sprintf(
        '"redeemDate":
          "%s"
                ',
        self$`redeemDate`
        )},
        if (!is.null(self$`startTime`)) {
        sprintf(
        '"startTime":
          %d
                ',
        self$`startTime`
        )},
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
          "%s"
                ',
        self$`status`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          "%s"
                ',
        self$`type`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse20081Json) {
      InlineResponse20081Object <- jsonlite::fromJSON(InlineResponse20081Json)
      self$`asset` <- InlineResponse20081Object$`asset`
      self$`canTransfer` <- InlineResponse20081Object$`canTransfer`
      self$`createTimestamp` <- InlineResponse20081Object$`createTimestamp`
      self$`duration` <- InlineResponse20081Object$`duration`
      self$`endTime` <- InlineResponse20081Object$`endTime`
      self$`interest` <- InlineResponse20081Object$`interest`
      self$`interestRate` <- InlineResponse20081Object$`interestRate`
      self$`lot` <- InlineResponse20081Object$`lot`
      self$`positionId` <- InlineResponse20081Object$`positionId`
      self$`principal` <- InlineResponse20081Object$`principal`
      self$`projectId` <- InlineResponse20081Object$`projectId`
      self$`projectName` <- InlineResponse20081Object$`projectName`
      self$`purchaseTime` <- InlineResponse20081Object$`purchaseTime`
      self$`redeemDate` <- InlineResponse20081Object$`redeemDate`
      self$`startTime` <- InlineResponse20081Object$`startTime`
      self$`status` <- InlineResponse20081Object$`status`
      self$`type` <- InlineResponse20081Object$`type`
      self
    }
  )
)
