# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse20016
#'
#' @description InlineResponse20016 Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field calcTime  integer 
#'
#' @field price  character 
#'
#' @field symbol  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20016 <- R6::R6Class(
  'InlineResponse20016',
  public = list(
    `calcTime` = NULL,
    `price` = NULL,
    `symbol` = NULL,
    initialize = function(
        `calcTime`, `price`, `symbol`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`calcTime`)) {
        stopifnot(is.numeric(`calcTime`), length(`calcTime`) == 1)
        self$`calcTime` <- `calcTime`
      }
      if (!missing(`price`)) {
        stopifnot(is.character(`price`), length(`price`) == 1)
        self$`price` <- `price`
      }
      if (!missing(`symbol`)) {
        stopifnot(is.character(`symbol`), length(`symbol`) == 1)
        self$`symbol` <- `symbol`
      }
    },
    toJSON = function() {
      InlineResponse20016Object <- list()
      if (!is.null(self$`calcTime`)) {
        InlineResponse20016Object[['calcTime']] <-
          self$`calcTime`
      }
      if (!is.null(self$`price`)) {
        InlineResponse20016Object[['price']] <-
          self$`price`
      }
      if (!is.null(self$`symbol`)) {
        InlineResponse20016Object[['symbol']] <-
          self$`symbol`
      }

      InlineResponse20016Object
    },
    fromJSON = function(InlineResponse20016Json) {
      InlineResponse20016Object <- jsonlite::fromJSON(InlineResponse20016Json)
      if (!is.null(InlineResponse20016Object$`calcTime`)) {
        self$`calcTime` <- InlineResponse20016Object$`calcTime`
      }
      if (!is.null(InlineResponse20016Object$`price`)) {
        self$`price` <- InlineResponse20016Object$`price`
      }
      if (!is.null(InlineResponse20016Object$`symbol`)) {
        self$`symbol` <- InlineResponse20016Object$`symbol`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`calcTime`)) {
        sprintf(
        '"calcTime":
          %d
                ',
        self$`calcTime`
        )},
        if (!is.null(self$`price`)) {
        sprintf(
        '"price":
          "%s"
                ',
        self$`price`
        )},
        if (!is.null(self$`symbol`)) {
        sprintf(
        '"symbol":
          "%s"
                ',
        self$`symbol`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse20016Json) {
      InlineResponse20016Object <- jsonlite::fromJSON(InlineResponse20016Json)
      self$`calcTime` <- InlineResponse20016Object$`calcTime`
      self$`price` <- InlineResponse20016Object$`price`
      self$`symbol` <- InlineResponse20016Object$`symbol`
      self
    }
  )
)
