# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse20073
#'
#' @description InlineResponse20073 Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field code  character 
#'
#' @field message  character 
#'
#' @field data  list( \link{InlineResponse20073Data} ) 
#'
#' @field total  integer 
#'
#' @field success  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20073 <- R6::R6Class(
  'InlineResponse20073',
  public = list(
    `code` = NULL,
    `message` = NULL,
    `data` = NULL,
    `total` = NULL,
    `success` = NULL,
    initialize = function(
        `code`, `message`, `data`, `total`, `success`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`code`)) {
        stopifnot(is.character(`code`), length(`code`) == 1)
        self$`code` <- `code`
      }
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!missing(`data`)) {
        stopifnot(is.vector(`data`), length(`data`) != 0)
        sapply(`data`, function(x) stopifnot(R6::is.R6(x)))
        self$`data` <- `data`
      }
      if (!missing(`total`)) {
        stopifnot(is.numeric(`total`), length(`total`) == 1)
        self$`total` <- `total`
      }
      if (!missing(`success`)) {
        stopifnot(is.logical(`success`), length(`success`) == 1)
        self$`success` <- `success`
      }
    },
    toJSON = function() {
      InlineResponse20073Object <- list()
      if (!is.null(self$`code`)) {
        InlineResponse20073Object[['code']] <-
          self$`code`
      }
      if (!is.null(self$`message`)) {
        InlineResponse20073Object[['message']] <-
          self$`message`
      }
      if (!is.null(self$`data`)) {
        InlineResponse20073Object[['data']] <-
          lapply(self$`data`, function(x) x$toJSON())
      }
      if (!is.null(self$`total`)) {
        InlineResponse20073Object[['total']] <-
          self$`total`
      }
      if (!is.null(self$`success`)) {
        InlineResponse20073Object[['success']] <-
          self$`success`
      }

      InlineResponse20073Object
    },
    fromJSON = function(InlineResponse20073Json) {
      InlineResponse20073Object <- jsonlite::fromJSON(InlineResponse20073Json)
      if (!is.null(InlineResponse20073Object$`code`)) {
        self$`code` <- InlineResponse20073Object$`code`
      }
      if (!is.null(InlineResponse20073Object$`message`)) {
        self$`message` <- InlineResponse20073Object$`message`
      }
      if (!is.null(InlineResponse20073Object$`data`)) {
        self$`data` <- ApiClient$new()$deserializeObj(InlineResponse20073Object$`data`, "array[InlineResponse20073Data]", loadNamespace("binanceRapi"))
      }
      if (!is.null(InlineResponse20073Object$`total`)) {
        self$`total` <- InlineResponse20073Object$`total`
      }
      if (!is.null(InlineResponse20073Object$`success`)) {
        self$`success` <- InlineResponse20073Object$`success`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`code`)) {
        sprintf(
        '"code":
          "%s"
                ',
        self$`code`
        )},
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        self$`message`
        )},
        if (!is.null(self$`data`)) {
        sprintf(
        '"data":
        [%s]
',
        paste(sapply(self$`data`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`total`)) {
        sprintf(
        '"total":
          %d
                ',
        self$`total`
        )},
        if (!is.null(self$`success`)) {
        sprintf(
        '"success":
          %s
                ',
        tolower(self$`success`)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse20073Json) {
      InlineResponse20073Object <- jsonlite::fromJSON(InlineResponse20073Json)
      self$`code` <- InlineResponse20073Object$`code`
      self$`message` <- InlineResponse20073Object$`message`
      self$`data` <- ApiClient$new()$deserializeObj(InlineResponse20073Object$`data`, "array[InlineResponse20073Data]", loadNamespace("binanceRapi"))
      self$`total` <- InlineResponse20073Object$`total`
      self$`success` <- InlineResponse20073Object$`success`
      self
    }
  )
)
