# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse20047
#'
#' @description InlineResponse20047 Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field subAccounts  list( \link{InlineResponse20047SubAccounts} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20047 <- R6::R6Class(
  'InlineResponse20047',
  public = list(
    `subAccounts` = NULL,
    initialize = function(
        `subAccounts`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`subAccounts`)) {
        stopifnot(is.vector(`subAccounts`), length(`subAccounts`) != 0)
        sapply(`subAccounts`, function(x) stopifnot(R6::is.R6(x)))
        self$`subAccounts` <- `subAccounts`
      }
    },
    toJSON = function() {
      InlineResponse20047Object <- list()
      if (!is.null(self$`subAccounts`)) {
        InlineResponse20047Object[['subAccounts']] <-
          lapply(self$`subAccounts`, function(x) x$toJSON())
      }

      InlineResponse20047Object
    },
    fromJSON = function(InlineResponse20047Json) {
      InlineResponse20047Object <- jsonlite::fromJSON(InlineResponse20047Json)
      if (!is.null(InlineResponse20047Object$`subAccounts`)) {
        self$`subAccounts` <- ApiClient$new()$deserializeObj(InlineResponse20047Object$`subAccounts`, "array[InlineResponse20047SubAccounts]", loadNamespace("binanceRapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`subAccounts`)) {
        sprintf(
        '"subAccounts":
        [%s]
',
        paste(sapply(self$`subAccounts`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse20047Json) {
      InlineResponse20047Object <- jsonlite::fromJSON(InlineResponse20047Json)
      self$`subAccounts` <- ApiClient$new()$deserializeObj(InlineResponse20047Object$`subAccounts`, "array[InlineResponse20047SubAccounts]", loadNamespace("binanceRapi"))
      self
    }
  )
)
