# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse20040
#'
#' @description InlineResponse20040 Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field CTR  \link{InlineResponse20040CTR} 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20040 <- R6::R6Class(
  'InlineResponse20040',
  public = list(
    `CTR` = NULL,
    initialize = function(
        `CTR`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`CTR`)) {
        stopifnot(R6::is.R6(`CTR`))
        self$`CTR` <- `CTR`
      }
    },
    toJSON = function() {
      InlineResponse20040Object <- list()
      if (!is.null(self$`CTR`)) {
        InlineResponse20040Object[['CTR']] <-
          self$`CTR`$toJSON()
      }

      InlineResponse20040Object
    },
    fromJSON = function(InlineResponse20040Json) {
      InlineResponse20040Object <- jsonlite::fromJSON(InlineResponse20040Json)
      if (!is.null(InlineResponse20040Object$`CTR`)) {
        CTRObject <- InlineResponse20040CTR$new()
        CTRObject$fromJSON(jsonlite::toJSON(InlineResponse20040Object$CTR, auto_unbox = TRUE, digits = NA))
        self$`CTR` <- CTRObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`CTR`)) {
        sprintf(
        '"CTR":
        %s
        ',
        jsonlite::toJSON(self$`CTR`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse20040Json) {
      InlineResponse20040Object <- jsonlite::fromJSON(InlineResponse20040Json)
      self$`CTR` <- InlineResponse20040CTR$new()$fromJSON(jsonlite::toJSON(InlineResponse20040Object$CTR, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
