# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse200108
#'
#' @description InlineResponse200108 Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field swapId  integer 
#'
#' @field swapTime  integer 
#'
#' @field status  integer 
#'
#' @field quoteAsset  character 
#'
#' @field baseAsset  character 
#'
#' @field quoteQty  numeric 
#'
#' @field baseQty  numeric 
#'
#' @field price  numeric 
#'
#' @field fee  numeric 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse200108 <- R6::R6Class(
  'InlineResponse200108',
  public = list(
    `swapId` = NULL,
    `swapTime` = NULL,
    `status` = NULL,
    `quoteAsset` = NULL,
    `baseAsset` = NULL,
    `quoteQty` = NULL,
    `baseQty` = NULL,
    `price` = NULL,
    `fee` = NULL,
    initialize = function(
        `swapId`, `swapTime`, `status`, `quoteAsset`, `baseAsset`, `quoteQty`, `baseQty`, `price`, `fee`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`swapId`)) {
        stopifnot(is.numeric(`swapId`), length(`swapId`) == 1)
        self$`swapId` <- `swapId`
      }
      if (!missing(`swapTime`)) {
        stopifnot(is.numeric(`swapTime`), length(`swapTime`) == 1)
        self$`swapTime` <- `swapTime`
      }
      if (!missing(`status`)) {
        stopifnot(is.numeric(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!missing(`quoteAsset`)) {
        stopifnot(is.character(`quoteAsset`), length(`quoteAsset`) == 1)
        self$`quoteAsset` <- `quoteAsset`
      }
      if (!missing(`baseAsset`)) {
        stopifnot(is.character(`baseAsset`), length(`baseAsset`) == 1)
        self$`baseAsset` <- `baseAsset`
      }
      if (!missing(`quoteQty`)) {
        stopifnot(is.numeric(`quoteQty`), length(`quoteQty`) == 1)
        self$`quoteQty` <- `quoteQty`
      }
      if (!missing(`baseQty`)) {
        stopifnot(is.numeric(`baseQty`), length(`baseQty`) == 1)
        self$`baseQty` <- `baseQty`
      }
      if (!missing(`price`)) {
        stopifnot(is.numeric(`price`), length(`price`) == 1)
        self$`price` <- `price`
      }
      if (!missing(`fee`)) {
        stopifnot(is.numeric(`fee`), length(`fee`) == 1)
        self$`fee` <- `fee`
      }
    },
    toJSON = function() {
      InlineResponse200108Object <- list()
      if (!is.null(self$`swapId`)) {
        InlineResponse200108Object[['swapId']] <-
          self$`swapId`
      }
      if (!is.null(self$`swapTime`)) {
        InlineResponse200108Object[['swapTime']] <-
          self$`swapTime`
      }
      if (!is.null(self$`status`)) {
        InlineResponse200108Object[['status']] <-
          self$`status`
      }
      if (!is.null(self$`quoteAsset`)) {
        InlineResponse200108Object[['quoteAsset']] <-
          self$`quoteAsset`
      }
      if (!is.null(self$`baseAsset`)) {
        InlineResponse200108Object[['baseAsset']] <-
          self$`baseAsset`
      }
      if (!is.null(self$`quoteQty`)) {
        InlineResponse200108Object[['quoteQty']] <-
          self$`quoteQty`
      }
      if (!is.null(self$`baseQty`)) {
        InlineResponse200108Object[['baseQty']] <-
          self$`baseQty`
      }
      if (!is.null(self$`price`)) {
        InlineResponse200108Object[['price']] <-
          self$`price`
      }
      if (!is.null(self$`fee`)) {
        InlineResponse200108Object[['fee']] <-
          self$`fee`
      }

      InlineResponse200108Object
    },
    fromJSON = function(InlineResponse200108Json) {
      InlineResponse200108Object <- jsonlite::fromJSON(InlineResponse200108Json)
      if (!is.null(InlineResponse200108Object$`swapId`)) {
        self$`swapId` <- InlineResponse200108Object$`swapId`
      }
      if (!is.null(InlineResponse200108Object$`swapTime`)) {
        self$`swapTime` <- InlineResponse200108Object$`swapTime`
      }
      if (!is.null(InlineResponse200108Object$`status`)) {
        self$`status` <- InlineResponse200108Object$`status`
      }
      if (!is.null(InlineResponse200108Object$`quoteAsset`)) {
        self$`quoteAsset` <- InlineResponse200108Object$`quoteAsset`
      }
      if (!is.null(InlineResponse200108Object$`baseAsset`)) {
        self$`baseAsset` <- InlineResponse200108Object$`baseAsset`
      }
      if (!is.null(InlineResponse200108Object$`quoteQty`)) {
        self$`quoteQty` <- InlineResponse200108Object$`quoteQty`
      }
      if (!is.null(InlineResponse200108Object$`baseQty`)) {
        self$`baseQty` <- InlineResponse200108Object$`baseQty`
      }
      if (!is.null(InlineResponse200108Object$`price`)) {
        self$`price` <- InlineResponse200108Object$`price`
      }
      if (!is.null(InlineResponse200108Object$`fee`)) {
        self$`fee` <- InlineResponse200108Object$`fee`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`swapId`)) {
        sprintf(
        '"swapId":
          %d
                ',
        self$`swapId`
        )},
        if (!is.null(self$`swapTime`)) {
        sprintf(
        '"swapTime":
          %d
                ',
        self$`swapTime`
        )},
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
          %d
                ',
        self$`status`
        )},
        if (!is.null(self$`quoteAsset`)) {
        sprintf(
        '"quoteAsset":
          "%s"
                ',
        self$`quoteAsset`
        )},
        if (!is.null(self$`baseAsset`)) {
        sprintf(
        '"baseAsset":
          "%s"
                ',
        self$`baseAsset`
        )},
        if (!is.null(self$`quoteQty`)) {
        sprintf(
        '"quoteQty":
          %d
                ',
        self$`quoteQty`
        )},
        if (!is.null(self$`baseQty`)) {
        sprintf(
        '"baseQty":
          %d
                ',
        self$`baseQty`
        )},
        if (!is.null(self$`price`)) {
        sprintf(
        '"price":
          %d
                ',
        self$`price`
        )},
        if (!is.null(self$`fee`)) {
        sprintf(
        '"fee":
          %d
                ',
        self$`fee`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse200108Json) {
      InlineResponse200108Object <- jsonlite::fromJSON(InlineResponse200108Json)
      self$`swapId` <- InlineResponse200108Object$`swapId`
      self$`swapTime` <- InlineResponse200108Object$`swapTime`
      self$`status` <- InlineResponse200108Object$`status`
      self$`quoteAsset` <- InlineResponse200108Object$`quoteAsset`
      self$`baseAsset` <- InlineResponse200108Object$`baseAsset`
      self$`quoteQty` <- InlineResponse200108Object$`quoteQty`
      self$`baseQty` <- InlineResponse200108Object$`baseQty`
      self$`price` <- InlineResponse200108Object$`price`
      self$`fee` <- InlineResponse200108Object$`fee`
      self
    }
  )
)
