# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse200100
#'
#' @description InlineResponse200100 Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field code  integer 
#'
#' @field msg  character 
#'
#' @field data  integer 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse200100 <- R6::R6Class(
  'InlineResponse200100',
  public = list(
    `code` = NULL,
    `msg` = NULL,
    `data` = NULL,
    initialize = function(
        `code`, `msg`, `data`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`code`)) {
        stopifnot(is.numeric(`code`), length(`code`) == 1)
        self$`code` <- `code`
      }
      if (!missing(`msg`)) {
        stopifnot(is.character(`msg`), length(`msg`) == 1)
        self$`msg` <- `msg`
      }
      if (!missing(`data`)) {
        stopifnot(is.numeric(`data`), length(`data`) == 1)
        self$`data` <- `data`
      }
    },
    toJSON = function() {
      InlineResponse200100Object <- list()
      if (!is.null(self$`code`)) {
        InlineResponse200100Object[['code']] <-
          self$`code`
      }
      if (!is.null(self$`msg`)) {
        InlineResponse200100Object[['msg']] <-
          self$`msg`
      }
      if (!is.null(self$`data`)) {
        InlineResponse200100Object[['data']] <-
          self$`data`
      }

      InlineResponse200100Object
    },
    fromJSON = function(InlineResponse200100Json) {
      InlineResponse200100Object <- jsonlite::fromJSON(InlineResponse200100Json)
      if (!is.null(InlineResponse200100Object$`code`)) {
        self$`code` <- InlineResponse200100Object$`code`
      }
      if (!is.null(InlineResponse200100Object$`msg`)) {
        self$`msg` <- InlineResponse200100Object$`msg`
      }
      if (!is.null(InlineResponse200100Object$`data`)) {
        self$`data` <- InlineResponse200100Object$`data`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`code`)) {
        sprintf(
        '"code":
          %d
                ',
        self$`code`
        )},
        if (!is.null(self$`msg`)) {
        sprintf(
        '"msg":
          "%s"
                ',
        self$`msg`
        )},
        if (!is.null(self$`data`)) {
        sprintf(
        '"data":
          %d
                ',
        self$`data`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse200100Json) {
      InlineResponse200100Object <- jsonlite::fromJSON(InlineResponse200100Json)
      self$`code` <- InlineResponse200100Object$`code`
      self$`msg` <- InlineResponse200100Object$`msg`
      self$`data` <- InlineResponse200100Object$`data`
      self
    }
  )
)
