# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse20054Balances
#'
#' @description InlineResponse20054Balances Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field asset  character 
#'
#' @field free  integer 
#'
#' @field locked  integer 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20054Balances <- R6::R6Class(
  'InlineResponse20054Balances',
  public = list(
    `asset` = NULL,
    `free` = NULL,
    `locked` = NULL,
    initialize = function(
        `asset`, `free`, `locked`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`asset`)) {
        stopifnot(is.character(`asset`), length(`asset`) == 1)
        self$`asset` <- `asset`
      }
      if (!missing(`free`)) {
        stopifnot(is.numeric(`free`), length(`free`) == 1)
        self$`free` <- `free`
      }
      if (!missing(`locked`)) {
        stopifnot(is.numeric(`locked`), length(`locked`) == 1)
        self$`locked` <- `locked`
      }
    },
    toJSON = function() {
      InlineResponse20054BalancesObject <- list()
      if (!is.null(self$`asset`)) {
        InlineResponse20054BalancesObject[['asset']] <-
          self$`asset`
      }
      if (!is.null(self$`free`)) {
        InlineResponse20054BalancesObject[['free']] <-
          self$`free`
      }
      if (!is.null(self$`locked`)) {
        InlineResponse20054BalancesObject[['locked']] <-
          self$`locked`
      }

      InlineResponse20054BalancesObject
    },
    fromJSON = function(InlineResponse20054BalancesJson) {
      InlineResponse20054BalancesObject <- jsonlite::fromJSON(InlineResponse20054BalancesJson)
      if (!is.null(InlineResponse20054BalancesObject$`asset`)) {
        self$`asset` <- InlineResponse20054BalancesObject$`asset`
      }
      if (!is.null(InlineResponse20054BalancesObject$`free`)) {
        self$`free` <- InlineResponse20054BalancesObject$`free`
      }
      if (!is.null(InlineResponse20054BalancesObject$`locked`)) {
        self$`locked` <- InlineResponse20054BalancesObject$`locked`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`asset`)) {
        sprintf(
        '"asset":
          "%s"
                ',
        self$`asset`
        )},
        if (!is.null(self$`free`)) {
        sprintf(
        '"free":
          %d
                ',
        self$`free`
        )},
        if (!is.null(self$`locked`)) {
        sprintf(
        '"locked":
          %d
                ',
        self$`locked`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse20054BalancesJson) {
      InlineResponse20054BalancesObject <- jsonlite::fromJSON(InlineResponse20054BalancesJson)
      self$`asset` <- InlineResponse20054BalancesObject$`asset`
      self$`free` <- InlineResponse20054BalancesObject$`free`
      self$`locked` <- InlineResponse20054BalancesObject$`locked`
      self
    }
  )
)
