# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Rebate operations
#' @description binanceRapi.Rebate
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ SapiV1RebateTaxQueryGet } \emph{ Get Spot Rebate History Records (USER_DATA) }
#' - The max interval between startTime and endTime is 90 days. - If startTime and endTime are not sent, the recent 7 days&#39; data will be returned. - The earliest startTime is supported on June 10, 2020  Weight(UID): 3000
#'
#' \itemize{
#' \item \emph{ @param } timestamp integer
#' \item \emph{ @param } signature character
#' \item \emph{ @param } start.time integer
#' \item \emph{ @param } end.time integer
#' \item \emph{ @param } page integer
#' \item \emph{ @param } recv.window integer
#' \item \emph{ @returnType } \link{InlineResponse200122} \cr
#'
#'
#' \item status code : 200 | Rebate History
#'
#' \item return type : InlineResponse200122 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad Request
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized Request
#'
#' \item return type : Error 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  SapiV1RebateTaxQueryGet  ####################
#'
#' library(binanceRapi)
#' var.timestamp <- 56 # integer | UTC timestamp in ms
#' var.signature <- 'signature_example' # character | Signature
#' var.start.time <- 56 # integer | UTC timestamp in ms
#' var.end.time <- 56 # integer | UTC timestamp in ms
#' var.page <- 1 # integer | default 1
#' var.recv.window <- 5000 # integer | The value cannot be greater than 60000
#'
#' #Get Spot Rebate History Records (USER_DATA)
#' api.instance <- RebateApi$new()
#'
#' #Configure API key authorization: ApiKeyAuth
#' api.instance$apiClient$apiKeys['X-MBX-APIKEY'] <- 'TODO_YOUR_API_KEY';
#'
#' result <- api.instance$SapiV1RebateTaxQueryGet(var.timestamp, var.signature, start.time=var.start.time, end.time=var.end.time, page=var.page, recv.window=var.recv.window)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
RebateApi <- R6::R6Class(
  'RebateApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    SapiV1RebateTaxQueryGet = function(timestamp, signature, start.time=NULL, end.time=NULL, page=NULL, recv.window=NULL, ...){
      apiResponse <- self$SapiV1RebateTaxQueryGetWithHttpInfo(timestamp, signature, start.time, end.time, page, recv.window, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    SapiV1RebateTaxQueryGetWithHttpInfo = function(timestamp, signature, start.time=NULL, end.time=NULL, page=NULL, recv.window=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`timestamp`)) {
        stop("Missing required parameter `timestamp`.")
      }

      if (missing(`signature`)) {
        stop("Missing required parameter `signature`.")
      }

      queryParams['startTime'] <- start.time

      queryParams['endTime'] <- end.time

      queryParams['page'] <- page

      queryParams['recvWindow'] <- recv.window

      queryParams['timestamp'] <- timestamp

      queryParams['signature'] <- signature

      body <- NULL
      urlPath <- "/sapi/v1/rebate/taxQuery"
      # API key authentication
      if ("X-MBX-APIKEY" %in% names(self$apiClient$apiKeys) && nchar(self$apiClient$apiKeys["X-MBX-APIKEY"]) > 0) {
        headerParams['X-MBX-APIKEY'] <- paste(unlist(self$apiClient$apiKeys["X-MBX-APIKEY"]), collapse='')
      }

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "InlineResponse200122", loadNamespace("binanceRapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
