# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SapiV1BswapLiquidityLiquidity
#'
#' @description SapiV1BswapLiquidityLiquidity Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field BUSD  numeric 
#'
#' @field USDT  numeric 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SapiV1BswapLiquidityLiquidity <- R6::R6Class(
  'SapiV1BswapLiquidityLiquidity',
  public = list(
    `BUSD` = NULL,
    `USDT` = NULL,
    initialize = function(
        `BUSD`, `USDT`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`BUSD`)) {
        stopifnot(is.numeric(`BUSD`), length(`BUSD`) == 1)
        self$`BUSD` <- `BUSD`
      }
      if (!missing(`USDT`)) {
        stopifnot(is.numeric(`USDT`), length(`USDT`) == 1)
        self$`USDT` <- `USDT`
      }
    },
    toJSON = function() {
      SapiV1BswapLiquidityLiquidityObject <- list()
      if (!is.null(self$`BUSD`)) {
        SapiV1BswapLiquidityLiquidityObject[['BUSD']] <-
          self$`BUSD`
      }
      if (!is.null(self$`USDT`)) {
        SapiV1BswapLiquidityLiquidityObject[['USDT']] <-
          self$`USDT`
      }

      SapiV1BswapLiquidityLiquidityObject
    },
    fromJSON = function(SapiV1BswapLiquidityLiquidityJson) {
      SapiV1BswapLiquidityLiquidityObject <- jsonlite::fromJSON(SapiV1BswapLiquidityLiquidityJson)
      if (!is.null(SapiV1BswapLiquidityLiquidityObject$`BUSD`)) {
        self$`BUSD` <- SapiV1BswapLiquidityLiquidityObject$`BUSD`
      }
      if (!is.null(SapiV1BswapLiquidityLiquidityObject$`USDT`)) {
        self$`USDT` <- SapiV1BswapLiquidityLiquidityObject$`USDT`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`BUSD`)) {
        sprintf(
        '"BUSD":
          %d
                ',
        self$`BUSD`
        )},
        if (!is.null(self$`USDT`)) {
        sprintf(
        '"USDT":
          %d
                ',
        self$`USDT`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SapiV1BswapLiquidityLiquidityJson) {
      SapiV1BswapLiquidityLiquidityObject <- jsonlite::fromJSON(SapiV1BswapLiquidityLiquidityJson)
      self$`BUSD` <- SapiV1BswapLiquidityLiquidityObject$`BUSD`
      self$`USDT` <- SapiV1BswapLiquidityLiquidityObject$`USDT`
      self
    }
  )
)
