# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SapiV1BswapPoolConfigureAssetConfigure
#'
#' @description SapiV1BswapPoolConfigureAssetConfigure Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field BUSD  \link{SapiV1BswapPoolConfigureAssetConfigureBUSD} 
#'
#' @field USDT  \link{SapiV1BswapPoolConfigureAssetConfigureBUSD} 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SapiV1BswapPoolConfigureAssetConfigure <- R6::R6Class(
  'SapiV1BswapPoolConfigureAssetConfigure',
  public = list(
    `BUSD` = NULL,
    `USDT` = NULL,
    initialize = function(
        `BUSD`, `USDT`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`BUSD`)) {
        stopifnot(R6::is.R6(`BUSD`))
        self$`BUSD` <- `BUSD`
      }
      if (!missing(`USDT`)) {
        stopifnot(R6::is.R6(`USDT`))
        self$`USDT` <- `USDT`
      }
    },
    toJSON = function() {
      SapiV1BswapPoolConfigureAssetConfigureObject <- list()
      if (!is.null(self$`BUSD`)) {
        SapiV1BswapPoolConfigureAssetConfigureObject[['BUSD']] <-
          self$`BUSD`$toJSON()
      }
      if (!is.null(self$`USDT`)) {
        SapiV1BswapPoolConfigureAssetConfigureObject[['USDT']] <-
          self$`USDT`$toJSON()
      }

      SapiV1BswapPoolConfigureAssetConfigureObject
    },
    fromJSON = function(SapiV1BswapPoolConfigureAssetConfigureJson) {
      SapiV1BswapPoolConfigureAssetConfigureObject <- jsonlite::fromJSON(SapiV1BswapPoolConfigureAssetConfigureJson)
      if (!is.null(SapiV1BswapPoolConfigureAssetConfigureObject$`BUSD`)) {
        BUSDObject <- SapiV1BswapPoolConfigureAssetConfigureBUSD$new()
        BUSDObject$fromJSON(jsonlite::toJSON(SapiV1BswapPoolConfigureAssetConfigureObject$BUSD, auto_unbox = TRUE, digits = NA))
        self$`BUSD` <- BUSDObject
      }
      if (!is.null(SapiV1BswapPoolConfigureAssetConfigureObject$`USDT`)) {
        USDTObject <- SapiV1BswapPoolConfigureAssetConfigureBUSD$new()
        USDTObject$fromJSON(jsonlite::toJSON(SapiV1BswapPoolConfigureAssetConfigureObject$USDT, auto_unbox = TRUE, digits = NA))
        self$`USDT` <- USDTObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`BUSD`)) {
        sprintf(
        '"BUSD":
        %s
        ',
        jsonlite::toJSON(self$`BUSD`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`USDT`)) {
        sprintf(
        '"USDT":
        %s
        ',
        jsonlite::toJSON(self$`USDT`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SapiV1BswapPoolConfigureAssetConfigureJson) {
      SapiV1BswapPoolConfigureAssetConfigureObject <- jsonlite::fromJSON(SapiV1BswapPoolConfigureAssetConfigureJson)
      self$`BUSD` <- SapiV1BswapPoolConfigureAssetConfigureBUSD$new()$fromJSON(jsonlite::toJSON(SapiV1BswapPoolConfigureAssetConfigureObject$BUSD, auto_unbox = TRUE, digits = NA))
      self$`USDT` <- SapiV1BswapPoolConfigureAssetConfigureBUSD$new()$fromJSON(jsonlite::toJSON(SapiV1BswapPoolConfigureAssetConfigureObject$USDT, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
