# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SapiV1MarginIsolatedMarginDataData
#'
#' @description SapiV1MarginIsolatedMarginDataData Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field coin  character [optional]
#'
#' @field dailyInterest  character [optional]
#'
#' @field borrowLimit  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SapiV1MarginIsolatedMarginDataData <- R6::R6Class(
  'SapiV1MarginIsolatedMarginDataData',
  public = list(
    `coin` = NULL,
    `dailyInterest` = NULL,
    `borrowLimit` = NULL,
    initialize = function(
        `coin`=NULL, `dailyInterest`=NULL, `borrowLimit`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`coin`)) {
        stopifnot(is.character(`coin`), length(`coin`) == 1)
        self$`coin` <- `coin`
      }
      if (!is.null(`dailyInterest`)) {
        stopifnot(is.character(`dailyInterest`), length(`dailyInterest`) == 1)
        self$`dailyInterest` <- `dailyInterest`
      }
      if (!is.null(`borrowLimit`)) {
        stopifnot(is.character(`borrowLimit`), length(`borrowLimit`) == 1)
        self$`borrowLimit` <- `borrowLimit`
      }
    },
    toJSON = function() {
      SapiV1MarginIsolatedMarginDataDataObject <- list()
      if (!is.null(self$`coin`)) {
        SapiV1MarginIsolatedMarginDataDataObject[['coin']] <-
          self$`coin`
      }
      if (!is.null(self$`dailyInterest`)) {
        SapiV1MarginIsolatedMarginDataDataObject[['dailyInterest']] <-
          self$`dailyInterest`
      }
      if (!is.null(self$`borrowLimit`)) {
        SapiV1MarginIsolatedMarginDataDataObject[['borrowLimit']] <-
          self$`borrowLimit`
      }

      SapiV1MarginIsolatedMarginDataDataObject
    },
    fromJSON = function(SapiV1MarginIsolatedMarginDataDataJson) {
      SapiV1MarginIsolatedMarginDataDataObject <- jsonlite::fromJSON(SapiV1MarginIsolatedMarginDataDataJson)
      if (!is.null(SapiV1MarginIsolatedMarginDataDataObject$`coin`)) {
        self$`coin` <- SapiV1MarginIsolatedMarginDataDataObject$`coin`
      }
      if (!is.null(SapiV1MarginIsolatedMarginDataDataObject$`dailyInterest`)) {
        self$`dailyInterest` <- SapiV1MarginIsolatedMarginDataDataObject$`dailyInterest`
      }
      if (!is.null(SapiV1MarginIsolatedMarginDataDataObject$`borrowLimit`)) {
        self$`borrowLimit` <- SapiV1MarginIsolatedMarginDataDataObject$`borrowLimit`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`coin`)) {
        sprintf(
        '"coin":
          "%s"
                ',
        self$`coin`
        )},
        if (!is.null(self$`dailyInterest`)) {
        sprintf(
        '"dailyInterest":
          "%s"
                ',
        self$`dailyInterest`
        )},
        if (!is.null(self$`borrowLimit`)) {
        sprintf(
        '"borrowLimit":
          "%s"
                ',
        self$`borrowLimit`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SapiV1MarginIsolatedMarginDataDataJson) {
      SapiV1MarginIsolatedMarginDataDataObject <- jsonlite::fromJSON(SapiV1MarginIsolatedMarginDataDataJson)
      self$`coin` <- SapiV1MarginIsolatedMarginDataDataObject$`coin`
      self$`dailyInterest` <- SapiV1MarginIsolatedMarginDataDataObject$`dailyInterest`
      self$`borrowLimit` <- SapiV1MarginIsolatedMarginDataDataObject$`borrowLimit`
      self
    }
  )
)
