# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SapiV1BlvtTokenInfoCurrentBaskets
#'
#' @description SapiV1BlvtTokenInfoCurrentBaskets Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field symbol  character 
#'
#' @field amount  character 
#'
#' @field notionalValue  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SapiV1BlvtTokenInfoCurrentBaskets <- R6::R6Class(
  'SapiV1BlvtTokenInfoCurrentBaskets',
  public = list(
    `symbol` = NULL,
    `amount` = NULL,
    `notionalValue` = NULL,
    initialize = function(
        `symbol`, `amount`, `notionalValue`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`symbol`)) {
        stopifnot(is.character(`symbol`), length(`symbol`) == 1)
        self$`symbol` <- `symbol`
      }
      if (!missing(`amount`)) {
        stopifnot(is.character(`amount`), length(`amount`) == 1)
        self$`amount` <- `amount`
      }
      if (!missing(`notionalValue`)) {
        stopifnot(is.character(`notionalValue`), length(`notionalValue`) == 1)
        self$`notionalValue` <- `notionalValue`
      }
    },
    toJSON = function() {
      SapiV1BlvtTokenInfoCurrentBasketsObject <- list()
      if (!is.null(self$`symbol`)) {
        SapiV1BlvtTokenInfoCurrentBasketsObject[['symbol']] <-
          self$`symbol`
      }
      if (!is.null(self$`amount`)) {
        SapiV1BlvtTokenInfoCurrentBasketsObject[['amount']] <-
          self$`amount`
      }
      if (!is.null(self$`notionalValue`)) {
        SapiV1BlvtTokenInfoCurrentBasketsObject[['notionalValue']] <-
          self$`notionalValue`
      }

      SapiV1BlvtTokenInfoCurrentBasketsObject
    },
    fromJSON = function(SapiV1BlvtTokenInfoCurrentBasketsJson) {
      SapiV1BlvtTokenInfoCurrentBasketsObject <- jsonlite::fromJSON(SapiV1BlvtTokenInfoCurrentBasketsJson)
      if (!is.null(SapiV1BlvtTokenInfoCurrentBasketsObject$`symbol`)) {
        self$`symbol` <- SapiV1BlvtTokenInfoCurrentBasketsObject$`symbol`
      }
      if (!is.null(SapiV1BlvtTokenInfoCurrentBasketsObject$`amount`)) {
        self$`amount` <- SapiV1BlvtTokenInfoCurrentBasketsObject$`amount`
      }
      if (!is.null(SapiV1BlvtTokenInfoCurrentBasketsObject$`notionalValue`)) {
        self$`notionalValue` <- SapiV1BlvtTokenInfoCurrentBasketsObject$`notionalValue`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`symbol`)) {
        sprintf(
        '"symbol":
          "%s"
                ',
        self$`symbol`
        )},
        if (!is.null(self$`amount`)) {
        sprintf(
        '"amount":
          "%s"
                ',
        self$`amount`
        )},
        if (!is.null(self$`notionalValue`)) {
        sprintf(
        '"notionalValue":
          "%s"
                ',
        self$`notionalValue`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SapiV1BlvtTokenInfoCurrentBasketsJson) {
      SapiV1BlvtTokenInfoCurrentBasketsObject <- jsonlite::fromJSON(SapiV1BlvtTokenInfoCurrentBasketsJson)
      self$`symbol` <- SapiV1BlvtTokenInfoCurrentBasketsObject$`symbol`
      self$`amount` <- SapiV1BlvtTokenInfoCurrentBasketsObject$`amount`
      self$`notionalValue` <- SapiV1BlvtTokenInfoCurrentBasketsObject$`notionalValue`
      self
    }
  )
)
