# Binance Public Spot API
#
# OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SubAccountCOINFuturesPositionRisk
#'
#' @description SubAccountCOINFuturesPositionRisk Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field deliveryPositionRiskVos  list( \link{SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SubAccountCOINFuturesPositionRisk <- R6::R6Class(
  'SubAccountCOINFuturesPositionRisk',
  public = list(
    `deliveryPositionRiskVos` = NULL,
    initialize = function(
        `deliveryPositionRiskVos`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`deliveryPositionRiskVos`)) {
        stopifnot(is.vector(`deliveryPositionRiskVos`), length(`deliveryPositionRiskVos`) != 0)
        sapply(`deliveryPositionRiskVos`, function(x) stopifnot(R6::is.R6(x)))
        self$`deliveryPositionRiskVos` <- `deliveryPositionRiskVos`
      }
    },
    toJSON = function() {
      SubAccountCOINFuturesPositionRiskObject <- list()
      if (!is.null(self$`deliveryPositionRiskVos`)) {
        SubAccountCOINFuturesPositionRiskObject[['deliveryPositionRiskVos']] <-
          lapply(self$`deliveryPositionRiskVos`, function(x) x$toJSON())
      }

      SubAccountCOINFuturesPositionRiskObject
    },
    fromJSON = function(SubAccountCOINFuturesPositionRiskJson) {
      SubAccountCOINFuturesPositionRiskObject <- jsonlite::fromJSON(SubAccountCOINFuturesPositionRiskJson)
      if (!is.null(SubAccountCOINFuturesPositionRiskObject$`deliveryPositionRiskVos`)) {
        self$`deliveryPositionRiskVos` <- ApiClient$new()$deserializeObj(SubAccountCOINFuturesPositionRiskObject$`deliveryPositionRiskVos`, "array[SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos]", loadNamespace("binanceRapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`deliveryPositionRiskVos`)) {
        sprintf(
        '"deliveryPositionRiskVos":
        [%s]
',
        paste(sapply(self$`deliveryPositionRiskVos`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SubAccountCOINFuturesPositionRiskJson) {
      SubAccountCOINFuturesPositionRiskObject <- jsonlite::fromJSON(SubAccountCOINFuturesPositionRiskJson)
      self$`deliveryPositionRiskVos` <- ApiClient$new()$deserializeObj(SubAccountCOINFuturesPositionRiskObject$`deliveryPositionRiskVos`, "array[SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos]", loadNamespace("binanceRapi"))
      self
    }
  )
)
